### PR TITLE
[DO NOT MERGE] Add some LN test cases like channels last TIMM would use

### PR DESCRIPTION
**Pull request by csarofeen**

### CODE REVIEW

**Comment by csarofeen** [comment]
@liqiangxl could you look at the sizes for these layer norm tests and check performance as part of your layer norm perf work?

**Comment by liqiangxl** [comment]
Reduction over `{24, 40, 48, 56, 72, 152, 184, 200, 368}` is very small. Previous work focused on very large reductions, e.g. over 10240 elements. Hope current work can further increase the performance on these small reductions.
Performance of nvFuser in the current branch:
image
raw data:
https://github.com/liqiangxl/playground/blob/main/debug/1883-ln-timm/timm_benckmark.csv

**Comment by naoyam** [comment]
Still nice speedups! Would be interesting to compare against Apex as well.

**Comment by naoyam** [comment]
@liqiangxl Do we have these LN sizes in the benchmarks? If not, can you please add them? I think we can close PR then, unless I'm missing something.

**Comment by liqiangxl** [comment]
moved to https://github.com/NVIDIA/Fuser/pull/68

**Pull request closed without merging**
