### PR TITLE
fixing removeProfilingNodes duplicated functions

### PR DESCRIPTION
**Pull request by jjsjann123**
Unfortunately there're two versions of removeProfilingNodes function and one of them is not cleaning up profile_ivalue nodes properly.
This leads to a dangling profile_ivalue node, which ended up being profiled multiple times and could give us false assert failures.

### CODE REVIEW

**Review by kevinstephano — APPROVED** [review]
I verified this works on JOC Bert Squad

**Comment by jjsjann123** [comment]
Local tests passing except for non-divisible split in layer_norm. I'm merging this PR

**Comment by jjsjann123** [comment]
Note to myself: push this PR separately to upstream!

**Comment by jjsjann123** [comment]
Tracking it here: https://github.com/pytorch/pytorch/pull/68804

**Pull request merged**
