### PR TITLE
flatten support - C++ only

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Support `torch.flatten`, which is similar to `torch.view(shape)`. This PR only adds C++ support. Python support will be added in follow-up PR.

I am planning to use this flatten support in my https://github.com/csarofeen/pytorch/pull/1512 to merge the last two dims to support applications like `long_tensor.view(torch.float)`.

### CODE REVIEW

**Review by rdspring1 — COMMENTED** [review]
Overall, the PR looks good. 

I think we should move some of the `flatten` logic to `TensorDomain`. We do something similar with `view` and `rfactor`.

https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/ir_nodes.cpp#L1593-L1601

**Review by naoyam — APPROVED** [review]
LGTM as well.

**Comment by zasdfgbnm** [comment]
@rdspring1 I moved the logic for the construction of a new `TensorDomain` into `TensorDomain`.

**Review by rdspring1 — APPROVED** [review]
LGTM

**Pull request merged**
