### PR TITLE
Fix a buffer overrun error

### PR DESCRIPTION
**Pull request by naoyam**
Fix a buffer overrun detected with asan

Also changed [i] to .at(i)

### CODE REVIEW

**Comment by jjsjann123** [comment]
linking https://github.com/pytorch/pytorch/pull/89584

**Comment by davidberard98** [comment]
@naoyam @jjsjann123 would you mind upstreaming this change? (or tell me if you'd prefer that I just copy the change over). I'm trying to fix some broken internal CI.

**Comment by naoyam** [comment]
> @naoyam @jjsjann123 would you mind upstreaming this change? (or tell me if you'd prefer that I just copy the change over). I'm trying to fix some broken internal CI.

I don't know the protocol of upstreaming, so please just copy the change.

**Review by csarofeen — APPROVED** [review]
LGTM

**Pull request merged**
