### PR TITLE
Temporarily disable cp.async.cg for now

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Looks like we are having some correctness error when using `cp.async.cg`. When using the `cg` version of `cp.async`, I see mismatches on a few elements of a row. I don't know why it is failing, but I checked the SASS, and the only difference is the `BYPASS` modifier in `LDGSTS`, and for other parts, they are exactly the same. I guess we are probably missing some sync somewhere?

Example error message:
```
Fusion returns wrong results! The result tensor has shape [2048,3456]. Mismatch happens at region result[599:600,1922:1984]
```

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
I think I found the reason why it is failing. The code we generate looks like:

```python
# prolog
for i in range(stage - 1):
  cp.async
  commit
wait stage - 2
# main loop
for i in range(size):
  cp.async
  compute
  wait stage - 2
  commit
```
This is wrong, because in the main loop, the commit happens after the wait, so the `wait stage - 2` in the main loop is really waiting for nothing. We should move the commit before compute.

**Review by naoyam — APPROVED** [review]

**Comment by naoyam** [comment]
> I think I found the reason why it is failing. The code we generate looks like:
> 
> ```python
> # prolog
> for i in range(stage - 1):
>   cp.async
>   commit
> wait stage - 2
> # main loop
> for i in range(size):
>   cp.async
>   compute
>   wait stage - 2
>   commit
> ```
> 
> This is wrong, because in the main loop, the commit happens after the wait, so the `wait stage - 2` in the main loop is really waiting for nothing. We should move the commit before compute.

Did it solve the issue? I don't know why `commit` is not done immediately after `cp.async`, but it seems still correct.

**Comment by zasdfgbnm** [comment]
> Did it solve the issue? I don't know why `commit` is not done immediately after `cp.async`, but it seems still correct.

Don't get a chance to try it yet. But why is this correct? Before entering the main loop, we committed `stage - 1` groups, and waited until only `stage - 2` groups are on the fly (that is, the first group is finished). Then after entering the first iteration of the main loop, we executed more `cp.async` without committing. So at this point, due to the previous `wait`, it is already guaranteed that we have at most `stage - 2` groups on the fly. Then the `wait stage - 2` will always finish immediately, without waiting for the data for the second iteration.

I am assuming the following: If I have
```
cp.async 1
cp.async 2
commit
cp.async 3
commit
cp.async 4
cp.async 5
...
wait 1
```
Then the `wait 1` will wait for `cp.async` at 1 and 2, not 3, because the  `1` in `wait 1` means 1 committed groups, in this case `{3}`, and 4 and 5 is not committed, so it does not count.

**Comment by naoyam** [comment]
> > Did it solve the issue? I don't know why `commit` is not done immediately after `cp.async`, but it seems still correct.
> 
> Don't get a chance to try it yet. But why is this correct? Before entering the main loop, we committed `stage - 1` groups, and waited until only `stage - 2` groups are on the fly (that is, the first group is finished). Then after entering the first iteration of the main loop, we executed more `cp.async` without committing. So at this point, due to the previous `wait`, it is already guaranteed that we have at most `stage - 2` groups on the fly. Then the `wait stage - 2` will always finish immediately, without waiting for the data for the second iteration.
> 
> I am assuming the following: If I have
> 
> ```
> cp.async 1
> cp.async 2
> commit
> cp.async 3
> commit
> cp.async 4
> cp.async 5
> ...
> wait 1
> ```
> 
> Then the `wait 1` will wait for `cp.async` at 1 and 2, not 3, because the `1` in `wait 1` means 1 committed groups, in this case `{3}`, and 4 and 5 is not committed, so it does not count.

Oh, you're right. I forgot the semantics of `wait stage - 2`.

**Comment by zasdfgbnm** [comment]
Merging this for now, will fix in a separate PR

**Comment by zasdfgbnm** [comment]
Oops.... I forget to change the SASS modifier test....

**Comment by naoyam** [comment]
That's a good indication of having effective tests!

**Pull request merged**
