### PR TITLE
Rewrite ExpressionEvaluator to use IterVisitor

### PR DESCRIPTION
**Pull request by tlemo**

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
Just a small nitpick to stay consistent with variable names:
`Statement* stmt`
`Val* val`
`Expr* expr`

Otherwise looks good to me.

**Comment by jjsjann123** [comment]
@tlemo Can you update the PR to fix variable name per comment? I'll merge it afterwards.

**Comment by jjsjann123** [comment]
update base branch looks scary due to diverged history.
We should rebase to the top of new dev branch `20_6_11_devel`. There shouldn't be any conflicts.

comments looks straight forward and have been handled in a follow up commit.

I'll merge once local tests cleared.

**Comment by tlemo** [comment]
Thanks @jjsjann123 for renaming the variables, I missed this conversation.

**Pull request merged**
