### PR TITLE
Add yet another reduction test

### PR DESCRIPTION
**Pull request by naoyam**

### CODE REVIEW

**Comment by jjsjann123** [comment]
Is this a broken test prior to the fixes?
I'm holding on to update this PR until `kevin_reduction` is merged.

**Comment by naoyam** [comment]
This is a test that exercises a bug that is recently fixed. Here's the fix: cab53acf1f8fd5d36b9a42643ac28da760c30727.

**Comment by jjsjann123** [comment]
changing base branch back to kevin_reduction. I'll rebase once it's merged.

**Comment by jjsjann123** [comment]
Closing this and replaced with #74

**Pull request closed without merging**
