### PR TITLE
Fix projected size calculation

### LINKED ISSUE #2381: Double counting of a tensor size in the calculation of projected buffers
When a tensor is both a persistent buffer by itself and an input to a projected buffer, its size is counted twice, leading to overestimation of projected buffer sizes.

See #2382 for a repro

### PR DESCRIPTION
**Pull request by naoyam**
Fix #2381

### CODE REVIEW

**Comment by naoyam** [comment]
On A100, these benchmarks appear to exhibit the overestimation:

```
"NvFuserScheduler_Softmax_BWD_Inner_fp16___GRAPH
"NvFuserScheduler_Softmax_BWD_Inner_fp32___GRAPH
"NvFuserScheduler_Softmax_BWD_Outer_fp16___GRAPH
"NvFuserScheduler_Softmax_BWD_Outer_fp32___GRAPH
```

I'll do perf comparisons just in case.

**Comment by naoyam** [comment]
Note that in the case of fp32, the calculated projected size is larger than the persistent size, e.g.:

```
NvFuserScheduler_Softmax_BWD_Inner_fp32___GRAPH/NvFuserScheduler_Softmax_BWD_Inner_fp32/16384/16384/manual_time
Persistent size: 131072, projected size: 196608
```

**Comment by naoyam** [comment]
I don't see major perf differences. Here's bandwidth comparison on A100 with the softmax BWD fp16 benchmarks.

image

The fp32 benchmarks don't seem to have any impact either (which is expected)

**Review by csarofeen — APPROVED** [review]
LGTM

**Pull request merged**
