### PR TITLE
Add approxmiate flag argument to test_autocast_nn_fp32

### PR DESCRIPTION
**Pull request by rdspring1**
Fixes 
```
======================================================================
ERROR: test_autocast_nn_fp32 (__main__.TestAutocastCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autocast.py", line 116, in test_autocast_nn_fp32
    self._run_autocast_outofplace(op, args, torch.float32, module=torch._C._nn, add_kwargs=maybe_kwargs)
  File "test/test_autocast.py", line 36, in _run_autocast_outofplace
    output = getattr(module, op)(*args, **add_kwargs)
TypeError: gelu() missing 1 required positional arguments: "approximate"

----------------------------------------------------------------------
```

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
LGTM

**Comment by rdspring1** [comment]
Should we wait for the upstream tanh gelu PR?

**Comment by csarofeen** [comment]
However you prefer.

**Comment by csarofeen** [comment]
@rdspring1 is this ready to merge in or is it superseded by upstream changes and can now be closed?

**Comment by rdspring1** [comment]
We should take the upstream changes, since we're not going with the boolean flag anymore.
However, it could address the default argument issue some users are having.

**Pull request closed without merging**
