### PR TITLE
Added python API `nvfuser.version()`

### LINKED ISSUE #2379: Feature request: version info exposed in Python api
Something like `nvfuser.version()` that returns version info. Useful to check for functionality and guard tests

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #2379 

Note: developers are supposed to bump the version number (`./third_party/nvfuser/version.txt`) when user facing APIs are updated.

nvfuser.version() returns a three digit version plus 7-digit sha from git commit. where it

    returns nvfuser version in format of a string 'm.n.p+git[7d-sha]'.
    We strip the git[7d-sha] and convert the string to
    `packaging.version.Version` for comparison. e.g. you can use it as:
        import nvfuser
        print(nvfuser.version())              # 0.0.1+git21df524
        nvfuser.version() == '0.0.1`          # True
        nvfuser.version() > '0.0.0`           # True
        from packaging.version import Version
        nvfuser.version() < Version('1.0.0')  # True
 
Currently the three digit version is hard coded inside `third_party/nvfuser/version.txt`. While the git sha is retrieved inside cmake, and the version string is then constructed and written to `thrid_party/nvfuser/python/version.py`

TODO:
We'll want to have something automatically in there to enforce API compatibility in the future.

### CODE REVIEW

**Comment by kevinstephano** [comment]
Could you just mention how the `version()` method works in the top comment?  What does the format look like?  It looks like comparisons work with 3 numbers, `0.0.0` but you mention it also returns git commit hash.

Also, how does the version get updated?  Is it happening automatically with a build?

**Comment by jjsjann123** [comment]
> Could you just mention how the `version()` method works in the top comment? What does the format look like? It looks like comparisons work with 3 numbers, `0.0.0` but you mention it also returns git commit hash.
> 
> Also, how does the version get updated? Is it happening automatically with a build?

Sorry for the lack of context :yum: 
Let me put something both in the PR as well as in the python files

**Comment by jjsjann123** [comment]
doc has been updated cc'ing @kevinstephano

**Review by kevinstephano — APPROVED** [review]
LGTM.

Just wanted to note the user is expected to bump the version typically based on changes to the `python_bindings.cpp` or `python/__init__.py`.

**Pull request merged**
