### PR TITLE
Temporarily disable test requring large shared memory.

### PR DESCRIPTION
**Pull request by shmsong**
This PR temporarily disables `FusionPersistentSoftmaxLocalSmem` on devices with <70KB of shared memory.

### CODE REVIEW

**Comment by naoyam** [comment]
I'm seeing the same error with PersistentNormLocalShared:

```
[ RUN      ] NVFuserTest.FusionPersistentNormLocalShared_CUDA
unknown file: Failure
C++ exception with description "(dynamic_smem_size) < (available_dynamic_smem_without_reconfiguration + additional_dynamic_smem_available_through_reconfiguration) INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":615, please report a bug to PyTorch. The total shared memory allocation is larger than available memory. Dynamic size: 66048. Available size: 49136. Configured smem size: 49152. Device limit size: 65536
```

**Comment by shmsong** [comment]
> I'm seeing the same error with PersistentNormLocalShared:
> 
> ```
> [ RUN      ] NVFuserTest.FusionPersistentNormLocalShared_CUDA
> unknown file: Failure
> C++ exception with description "(dynamic_smem_size) < (available_dynamic_smem_without_reconfiguration + additional_dynamic_smem_available_through_reconfiguration) INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":615, please report a bug to PyTorch. The total shared memory allocation is larger than available memory. Dynamic size: 66048. Available size: 49136. Configured smem size: 49152. Device limit size: 65536
> ```

OK. We can guard that test as well.

**Comment by shmsong** [comment]
These guards will be removed after #1792

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
