### PR TITLE
Fix tv parallelization

### LINKED ISSUE #757: Missing parallel broadcast
The decision whether `blockBroadcast` is used is done by looking at the parallel type of an IterDomain of the output Fusion TensorView, which may not have the correct parallel type when computed at another tensor. It should use the ComputeAtMap rather than just looking at the IterDomain of the tensor.

Repro:
```
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  auto tv1 = sum(tv0, {1});
  auto tv2 = broadcast(tv1, {false, true});
  auto tv3 = makeSymbolicTensor(2);
  fusion.addInput(tv3);
  auto tv4 = add(tv2, tv3);
  fusion.addOutput(tv4);

  fusion.printMath();
  fusion.printKernel();

  tv1->computeAt(tv4, -1);

  tv4->axis(-1)->parallelize(ParallelType::TIDx);
  tv1->axis(-1)->parallelize(ParallelType::TIDx);

  // Uncomment below, and the test passes. This explicit
  // parallelization of tv2 should not be necessary.
  // tv2->axis(-1)->parallelize(ParallelType::TIDx);
```

The problem happens with `tv2`. Its computeAt position is 2, so it should inherit the parallelization of `tv4` for both of the two axes, and thus it should generate a call to `blockBroadcast`. However, here's what's generated:

```
__global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 2> T3, Tensor<float, 2> T4) {
  alignas(4) extern __shared__ char array[];
  void* shared_mem = array;
  #pragma unroll 1
  for(size_t ki28 = 0; ki28 < T0.size[0]; ++ki28) {
    float T1[1];
    T1[0] = 0;
    blockReduce<true, false, false>(
      T1[0],
      T0[(ki28 * T0.stride[0]) + (threadIdx.x * T0.stride[1])],
      [](float &a, float b) { a = a + b; },
      threadIdx,
      blockDim,
      static_cast<float*>(shared_mem),
      true,
      float(0));
    float T2[1];
    if (((threadIdx.x == 0))) {
      T2[0]
         = T1[0];
    }
    if (((threadIdx.x == 0))) {
      T4[(ki28 * (1 * blockDim.x)) + (threadIdx.x * 1)]
        = T2[0]
        + T3[(ki28 * T3.stride[0]) + (threadIdx.x * T3.stride[1])];
    }
  }
}
```

Notice that `T2` does not use `blockBroadcast`. 

The problem can be worked around by explicitly parallelizing the second axis of `T2` as well.

The bug resides in getParallelBroadcastDomains, where we simply use a Fusion IterDomain of a Fusion TensorView.

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #757

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]

**Comment by naoyam** [comment]
It turned out this is actually not the right thing to do. The parallel map contains mappings created with the the forward-bcast-mismatch enabled, so for example, it would create a mapping between `I2*I1` of `t4` and `I1` of `t2`:

```
t0 = makeSymbolicTensor(1); // t0: [I1]
t1 = makeSymbolicTensor(2); // t1: [I2, I1]
t2 = t0 + 1; // t2: [I1]
t3 = broadcast(t2, {true, false}); // t3: [B1, I1]
t4 = t1 + t3; // t4: [I2, I1]
t4->merge(0, 1); // t4: [I2*I1]
t2->computeAt(t4, -1);
t4->axis(0)->parallelize(TIDx);
```

This PR would do `t2->axis(0)->parallelize(TIDx)` as the axis is mapped with the `t4` axis. However, this is a problem since that would mean `I2*I1 == blockDim.x` and `I1 == blockDim.x`.

**Comment by naoyam** [comment]
Ended up adding `ParallelTypeBitmap` to `kir::BroadcastOp`. See 9f9f902. This is the only way I can think of for properly finding the parallelism of `kir::BroadcastOp`. 

More broadly, I think a bigger problem is that we don't have straightforward way to know parallelism of `kir:TensorView` and `kir::IterDomain`. The truth only lies in the ComputeAt parallel map, which only exists at the lowering time. Referring to `kir::IterDomain::parallelType()` is not robust as it may not be the same as the real parallel type. We use that for codegen of `kir::ReductionOp`, where it is fortunately safe as there should be no reduction in the CA axes.

**Comment by csarofeen** [comment]
`I2*I1 == blockDim.x` and `I1 == blockDim.x` actually seems fine to me in this case.

`blockDim.x` should be set to the maximum size. I think the issue is that we substitute values in the IR for `blockDim.x` where we shouldn't. I think the original issue stems from the fact that a tensor size gets substituted for this value, and thread bindings can be ambiguous in the presence of broadcst. I'm uncertain we can resolve all cases.

**Comment by csarofeen** [comment]
I thought that was how we started down this path: https://github.com/csarofeen/pytorch/pull/622

**Review by csarofeen — CHANGES_REQUESTED** [review]
Clearing approval as looks like we should discuss/think about this more. Broadcast parallelism is definitely a complex topioc.

**Comment by naoyam** [comment]
The substitution is done here:

https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/kernel_ir.cpp#L100-L109

If we allow `I2*I1 == blockDim.x` and `I1 == blockDim.x`, the substitution is no longer valid.

I see two options:

1. Parallelize all `kir::IterDomain` when inferred from the computeAt map and stop the substitution. (ab83e3e)
2. Annotate `kir::BroadcastOp` (9f9f902)

I'd say the second option is more conservative. It only solves this particular problem with BroadcastOp. The first option may be more preferable as it conveys the parallelism information to KIR. However, there may be side effects as the substitution problem. 

The first option seems better to me from long-term perspectives.

**Comment by csarofeen** [comment]
Can you try 1 and run the reduction benchmark suite before and after to see if you find any serious perf regressions. We use a lot of tensor size information in our kernels anyways, I think removing the substitution shouldn't be significant, though I could definitely be wrong.

**Comment by naoyam** [comment]
@csarofeen Done. I changed `kir::IterDomain::extent()` to just return `extent_`, which is just the same as `rawExtent()`. All tests are working fine.

**Review by csarofeen — APPROVED** [review]

**Pull request merged**
