### PR TITLE
index_select/gather cache patch

### PR DESCRIPTION
**Pull request by jjsjann123**
patching index_select/gather on cache check to examine reduction dimension. (original issue exposed lightning)
Added python tests to verify the fix.
lintrunner to check FLAKE8 on nvfuser python code

### CODE REVIEW

**Comment by jjsjann123** [comment]
cc'ing @ftxj

**Comment by jjsjann123** [comment]
I'm guessing conflicts are coming from the excessive black clean up. Will resolve when I get a chance.

**Comment by ftxj** [comment]
> cc'ing @ftxj

Know the change, thanks!

**Review by kevinstephano — APPROVED** [review]
LGTM!

**Comment by jjsjann123** [comment]
devel is broken. I have the foul PR reverted and is running CI locally. I'll merge once CI finishes.

**Comment by jjsjann123** [comment]
CI passed. Merging this one

**Pull request merged**
