### PR TITLE
conv2d passes added to separate bias add

### PR DESCRIPTION
**Pull request by jjsjann123**
This PR adds an optimization pass that isolates the `bias` in `conv2d` into a stand-alone `add_optional` op, which allows fuser to absorb it. (Currently conv2d handles `add` as an inplace operation, so the fusion would be saving us an extra kernel launch)

There are two issues that this won't work with our current codebase:
1. conv2d is not autodiff-compatible, so if you are running training, it won't be useful.
2. On python side, `bias` in conv2d is annotated as `Optional[Tensor]` I have a local hack that disables that, but I don't know if it's safe to do so. I'll push that conversation with upstream in a separate thread.

### CODE REVIEW

**Comment by jjsjann123** [comment]
Hack for JIT parser that I was referring to: https://github.com/csarofeen/pytorch/commit/e3cd65c0400f64bd734e9efee2e7dbbc55e8e452

**Comment by csarofeen** [comment]
Is this PR [Do Not Review] and [Do Not Merge] then?

**Comment by jjsjann123** [comment]
> Is this PR [Do Not Review] and [Do Not Merge] then?

Kevin is reviewing this right now :wink:

**Review by kevinstephano — APPROVED** [review]
LGTM

**Pull request merged**
