### PR TITLE
Enable Transpose operation

### PR DESCRIPTION
**Pull request by rdspring1**
Enable `permute, transpose, and t` in python frontend

Requires: Transpose Scheduler

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
LGTM

**Comment by csarofeen** [comment]
@zasdfgbnm are we ready for this?

**Comment by rdspring1** [comment]
Note: This PR only enables transpose for Torchscript. We'll another PR for primTorch.

**Comment by zasdfgbnm** [comment]
Seeing a segfault at `test_nvfuser_correctness_permute_cuda_bool` looking into it

gdb shows the following stack trace, I am not sure if it is related
```C++
#0  0x00007fffc2c6ef91 in __cxxabiv1::__cxa_throw (obj=0x5556040f1d10, tinfo=0x7fffc167d0b8 <typeinfo for c10::Error>, 
    dest=0x7fffd7929030 <c10::Error::~Error()>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:81
#1  0x00007fffd7975e9f in c10::detail::torchCheckFail (func=0x7fff94e0b15f "getDebugState", 
    file=0x7fff94e0a6a5 "/home/gaoxiang/nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp", line=698, 
    msg=0x7fff94e0b16d "optimized_plan_ INTERNAL ASSERT FAILED at \"/home/gaoxiang/nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp\":698, please report a bug to PyTorch. ") at /home/gaoxiang/nvfuser2/c10/util/Exception.cpp:94
#2  0x00007fffc007375b in c10::detail::torchInternalAssertFail (func=0x7fff94e0b15f "getDebugState", 
    file=0x7fff94e0a6a5 "/home/gaoxiang/nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp", line=698, 
    condMsg=0x7fff94e0b16d "optimized_plan_ INTERNAL ASSERT FAILED at \"/home/gaoxiang/nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp\":698, please report a bug to PyTorch. ") at /home/gaoxiang/nvfuser/c10/util/Exception.h:441
#3  0x00007fff8f8a0bcf in torch::jit::ProfilingGraphExecutorImpl::getDebugState (this=0x5556037e08f0)
    at /home/gaoxiang/nvfuser/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp:698
#4  0x00007fff8f8508c1 in torch::jit::GraphExecutor::getDebugState (this=0x55560071fbf0)
    at /home/gaoxiang/nvfuser/torch/csrc/jit/runtime/graph_executor.cpp:842
#5  0x00007fffc09eafc0 in torch::jit::initJitScriptBindings(_object*)::$_59::operator()(torch::jit::StrongFunctionPtr const&) const (this=0x55555905cfb8, self=...) at /home/gaoxiang/nvfuser/torch/csrc/jit/python/script_init.cpp:1500
#6  0x00007fffc09eaf61 in pybind11::detail::argument_loader<torch::jit::StrongFunctionPtr const&>::call_impl<torch::jit::GraphExecutorState, torch::jit::initJitScriptBindings(_object*)::$_59&, 0ul, pybind11::detail::void_type>(torch::jit::initJitScriptBindings(_object*)::$_59&, std::integer_sequence<unsigned long, 0ul>, pybind11::detail::void_type&&) && (this=0x7fffffff9968, 
    f=...) at /home/gaoxiang/nvfuser/cmake/../third_party/pybind11/include/pybind11/cast.h:1441
#7  0x00007fffc09eaed6 in pybind11::detail::argument_loader<torch::jit::StrongFunctionPtr const&>::call<torch::jit::GraphExecutorState, pybind11::detail::void_type, torch::jit::initJitScriptBindings(_object*)::$_59&>(torch::jit::initJitScriptBindings(_object*)::$_59&) && (this=0x7fffffff9968, f=...)
    at /home/gaoxiang/nvfuser/cmake/../third_party/pybind11/include/pybind11/cast.h:1409
#8  0x00007fffc09ead98 in pybind11::cpp_function::initialize<torch::jit::initJitScriptBindings(_object*)::$_59, torch::jit::GraphExecutorState, torch::jit::StrongFunctionPtr const&, pybind11::name, pybind11::is_method, pybind11::sibling>(torch::jit::initJitScriptBindings(_object*)::$_59&&, torch::jit::GraphExecutorState (*)(torch::jit::StrongFunctionPtr const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#1}::operator()(pybind11::detail::function_call&) const (this=0x7fffffff9fd0, call=...)
    at /home/gaoxiang/nvfuser/cmake/../third_party/pybind11/include/pybind11/pybind11.h:249
#9  0x00007fffc09eac92 in pybind11::cpp_function::initialize<torch::jit::initJitScriptBindings(_object*)::$_59, torch::jit::GraphExecutorState, torch::jit::StrongFunctionPtr const&, pybind11::name, pybind11::is_method, pybind11::sibling>(torch::jit::initJitScriptBindings(_object*)::$_59&&, torch::jit::GraphExecutorState (*)(torch::jit::StrongFunctionPtr const&), pybind11::name cons--Type <RET> for more, q to quit, c to continue without paging--
t&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#1}::__invoke(pybind11::detail::function_call&) (call=...) at /home/gaoxiang/nvfuser/cmake/../third_party/pybind11/include/pybind11/pybind11.h:224
#10 0x00007fffbfe1ef07 in pybind11::cpp_function::dispatcher (self=0x7ffff6613660, args_in=0x7fff10918520, kwargs_in=0x0)
    at /home/gaoxiang/nvfuser/cmake/../third_party/pybind11/include/pybind11/pybind11.h:929
```

**Comment by rdspring1** [comment]
Hmm. I am seeing different errors between runs of the test.

```
RuntimeError: expanded_extent_ == nullptr || isBroadcast() 
INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/ir_internal_nodes.h":879, please report a bug to PyTorch.
Expanded extent is only relevant for strided broadcast dimensions yet found an expanded extent 
without a strided broadcast iter type.
```

```
RuntimeError: extent_ != nullptr INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/ir_internal_nodes.h":874, 
please report a bug to PyTorch.
```

SegFault:
```
0x00007fffaeac9bda in torch::jit::fuser::cuda::IterDomainBuilder::IterDomainBuilder(torch::jit::fuser::cuda::IterDomain const*) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
(gdb) bt
#0  0x00007fffaeac9bda in torch::jit::fuser::cuda::IterDomainBuilder::IterDomainBuilder(torch::jit::fuser::cuda::IterDomain const*) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#1  0x00007fffaeacafc7 in torch::jit::fuser::cuda::IterDomain::cloneWithoutRFactor() const () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#2  0x00007fffaeb91dad in torch::jit::fuser::cuda::permute(torch::jit::fuser::cuda::TensorView*, std::vector<long, std::allocator<long> > const&) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#3  0x00007fffaebb8187 in torch::jit::fuser::cuda::(anonymous namespace)::IrParser::registerJitOperator()::{lambda(torch::jit::Node const*, std::unordered_map<unsigned long, torch::jit::fuser::cuda::(anonymous namespace)::ValueHolder, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, torch::jit::fuser::cuda::(anonymous namespace)::ValueHolder> > >&)#89}::operator()(torch::jit::Node const*, std::unordered_map<unsigned long, torch::jit::fuser::cuda::(anonymous namespace)::ValueHolder, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, torch::jit::fuser::cuda::(anonymous namespace)::ValueHolder> > >&) const [clone .isra.0] () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#4  0x00007fffaebc44c9 in torch::jit::fuser::cuda::(anonymous namespace)::IrParser::parse() () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#5  0x00007fffaebc5124 in torch::jit::fuser::cuda::parseJitIR(std::shared_ptr<torch::jit::Graph> const&) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#6  0x00007fffaeafd776 in torch::jit::fuser::cuda::GraphCache::createFusion(std::shared_ptr<torch::jit::Graph> const&) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#7  0x00007fffaeafdb7b in torch::jit::fuser::cuda::GraphCache::GraphCache(std::shared_ptr<torch::jit::Graph> const&) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#8  0x00007fffaeb81d3a in torch::jit::fuser::cuda::compileCudaFusionGroup(torch::jit::Node*)::{lambda()#1}::operator()() const [clone .isra.0] () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#9  0x00007fffaeb82389 in torch::jit::fuser::cuda::compileCudaFusionGroup(torch::jit::Node*) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#10 0x00007fffaea6aeb8 in torch::jit::fuser::cuda::(anonymous namespace)::compileFusionRecursive(torch::jit::Block*) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#11 0x00007fffaea6ae52 in torch::jit::fuser::cuda::(anonymous namespace)::compileFusionRecursive(torch::jit::Block*) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#12 0x00007fffaea7e072 in torch::jit::fuser::cuda::CudaFuseGraph(std::shared_ptr<torch::jit::Graph>&) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so
#13 0x00007fffba7f9c3c in torch::jit::ProfilingGraphExecutorImpl::runNoGradOptimizations(std::shared_ptr<torch::jit::Graph>&, unsigned long) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#14 0x00007fffba7fe7b0 in torch::jit::ProfilingGraphExecutorImpl::runProfilingOptimizations(std::shared_ptr<torch::jit::Graph>&, unsigned long) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#15 0x00007fffba7ff58d in torch::jit::ProfilingGraphExecutorImpl::getOptimizedPlanFor(std::vector<c10::IValue, std::allocator<c10::IValue> >&, c10::optional<unsigned long>) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#16 0x00007fffba7ffc41 in torch::jit::ProfilingGraphExecutorImpl::getPlanFor(std::vector<c10::IValue, std::allocator<c10::IValue> >&, c10::optional<unsigned long>) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#17 0x00007fffba7b9afd in torch::jit::GraphExecutorImplBase::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#18 0x00007fffc167d63e in torch::jit::runAndInsertCall(torch::jit::Function&, torch::jit::tuple_slice const&, pybind11::kwargs const&, c10::optional<c10::IValue>, std::function<torch::jit::Value* (torch::jit::Graph&, torch::jit::MatchedSchema const&)> const&) ()
   from /home/rds4/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so
```

**Comment by rdspring1** [comment]
Ah, it is failing on these permute dimensions:

1. `((0, -2, -1, 1),)`
2. `((),)`

I will push a fix.

**Comment by zasdfgbnm** [comment]
Thanks for fixing!

**Comment by rdspring1** [comment]
@zasdfgbnm I fixed the segmentation errors, but now I am seeing this error.
```
RuntimeError: entry_it != disjointSetMap().end() 
INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/disjoint_set.h":259, 
please report a bug to PyTorch. 
Strict mapping failed on element: T0_g[ 0 ] either an error occured, or non strict mapping should have been used.
```

**Comment by zasdfgbnm** [comment]
I will take a look

**Comment by rdspring1** [comment]
I forgot to mention that the failure occurs when running all the permute correctness tests.

`python test_jit_cuda_fuser.py -k test_nvfuser_correctness_permute`

**Comment by zasdfgbnm** [comment]
The `entry_it != disjointSetMap().end()` error is fixed, but still it is a failure. The root cause seems to be because the fusion is empty:

```
Inputs:
  T0_g[ 0 ], bool
Outputs:
  T0_g[ 0 ], bool

%kernel_math {
}
```

**Comment by zasdfgbnm** [comment]
Is it possible to skip empty fusion from the TorchScript side?

**Review by zasdfgbnm — DISMISSED** [review]
Putting a request change to avoid accidental merge

**Comment by rdspring1** [comment]
There isn't a pass to skip empty fusions yet. Do we know why there are empty fusion groups happening?

**Comment by zasdfgbnm** [comment]
> There isn't a pass to skip empty fusions yet. Do we know why there are empty fusion groups happening?

I think it is explicitly written in the tests:

https://github.com/csarofeen/pytorch/blob/306d4a68f127dd1b854b749855e48ba23444ba60/torch/testing/_internal/common_methods_invocations.py#L4677-L4686

**Comment by zasdfgbnm** [comment]
Related issue/PR:
https://github.com/csarofeen/pytorch/issues/1808
https://github.com/csarofeen/pytorch/issues/1752
https://github.com/csarofeen/pytorch/pull/1835
Let me check if I can do anything to unblock this test

**Comment by rdspring1** [comment]
@zasdfgbnm I fixed the empty fusion by returning `set(x)` instead of `x` when the input is a scalar tensor.

**Review by zasdfgbnm — APPROVED** [review]

**Comment by zasdfgbnm** [comment]
@rdspring1 please merge if you think it is OK to do so

**Pull request merged**
