### PR TITLE
Normalization graph partition update

### PR DESCRIPTION
**Pull request by jjsjann123**
Add operator type in parser. This allows us to apply similar restriction on fusion pattern for normalization ops, similar to what we did with reduction.

### CODE REVIEW

**Comment by jjsjann123** [comment]
@rdspring1 This PR is to patch the parser rule for normalization. I mentioned it here in your original PR: https://github.com/csarofeen/pytorch/pull/440#discussion_r519774981

**Comment by rdspring1** [comment]
Could we use the `OperatorType` to select the schedule between `pointwise, reduction, and normalization`?

**Comment by jjsjann123** [comment]
We could.

In the ideal world, we would be able to merge operators with different type in arbitrary topology and that would require us to merge their operator type to correctly reflect the merged fusion type, which determines the schedule.

**Review by rdspring1 — APPROVED** [review]
LGTM.

So, we would need to pass the information from `IrParser `to `GraphCache `to `FusionExecutorCache`

**Comment by jjsjann123** [comment]
Test passed locally. Can you merge it for me since I cannot bypass flake8? @csarofeen

**Pull request merged**
