### PR TITLE
fixing removeOutputUsedOnlyInDtype pass

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes the bug where `removeOutputUsedOnlyInDtype` function erases outputs from fusion group.

The issue was introduced when the assumption that `prim::CudaFusionGroup` outputs would match the return from the nesting `prim::If` block. The assumption was broken when we introduced some mutation passes for batch_norm (reserved workspace and scalar output were put into the TorchScript graph).

Updated removal rule is to actually go over unused data, which is hopefully future proof. :crossed_fingers:

### CODE REVIEW

**Comment by jjsjann123** [comment]
Fixed this use case from Kevin:

```import torch                                                                                                               
from torch.nn import Module                                                                                                                                                                   
import torch.nn.functional as F                                                                                            
                                                                                                                           
torch._C._jit_set_nvfuser_enabled(True)                                                                                    
torch._C._jit_set_texpr_fuser_enabled(False)                                                                               
torch._C._jit_set_profiling_executor(True)                                                                                 
torch._C._jit_set_profiling_mode(True)                                                                                     
torch._C._jit_override_can_fuse_on_cpu(False)                                                                              
torch._C._jit_override_can_fuse_on_gpu(False)                                                                              
torch._C._jit_set_bailout_depth(20)                                                                                        
                                                                                                                           
class Fusion(Module):                                                                                                      
    def __init__(self):                                                                                                    
        super(Fusion, self).__init__()                                                                                     
        self.bn0 = torch.nn.BatchNorm2d(512)                                                                               
        self.bn1 = torch.nn.BatchNorm2d(512)                                                                               
                                                                                                                           
    def forward(self, inputs, resids):                                                                                     
        out1 = self.bn0(inputs)                                                                                            
        out2 = self.bn1(resids)                                                                                            
        return torch.relu(out1 + out2)                                                                                     
                                                                                                                           
if __name__ == "__main__" :                                                                                                
    inputs = torch.randn(256, 512, 28, 28, requires_grad=True, device="cuda", dtype=torch.float16).to(memory_format=torch.channels_last)
    resids = torch.randn(256, 512, 28, 28, requires_grad=True, device="cuda", dtype=torch.float16).to(memory_format=torch.channels_last)
                                                                                                                           
    model = Fusion()                                                                                                       
    model.to(memory_format=torch.channels_last)                                                                            
    model.cuda()                                                                                                           
    #model.half()                                                                                                          
                                                                                                                           
    jit_model = torch.jit.script(model)                                                                                    
    #jit_model = model #torch.jit.script(model)                                                                            
                                                                                                                           
    with torch.cuda.amp.autocast(True):                                                                                    
    #with torch.cuda.amp.autocast(False):                                                                                  
        out = None                                                                                                         
        for idx in range(5) :                                                                                              
            #if idx == 3 :                                                                                                 
            #    print(jit_model.graph_for(inputs, resids))                                                                
            out = jit_model.forward(inputs, resids)                                                                        
                                                                                                                           
        #print(out)                                                                                                        
        print(jit_model.graph_for(inputs, resids)) 
```

**Comment by jjsjann123** [comment]
Running CI now.
This PR should go in after #1228, since it needs the other fix as well.

**Comment by jjsjann123** [comment]
Tests passing! ready to go

**Comment by jjsjann123** [comment]
Tests passing again, good for review!

**Review by kevinstephano — APPROVED** [review]
LGTM

**Pull request merged**
