### PR TITLE
patching nvfuser conv cudnn test numerics mismatch

### PR DESCRIPTION
**Pull request by jjsjann123**
Tests failed on upstream, not yet in our devel branch. Disabling TF32 in the test, which creates numerical issue when validating outputs.

### CODE REVIEW

**Review by naoyam — COMMENTED** [review]
Can we just make it disabled by default?

**Comment by jjsjann123** [comment]
> Can we just make it disabled by default?

Are are talking about the scope of nvfuser tests?
we can try to put this in our `NVFuserTest`. I'm a little worried that this might interfere how other tests running in parallel....

https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Context.cpp#L35
We should probably change this to a thread_local instead....

**Review by csarofeen — APPROVED** [review]
Seems fine, would be nice to have it on by default.

**Comment by naoyam** [comment]
> > Can we just make it disabled by default?
> 
> Are are talking about the scope of nvfuser tests? we can try to put this in our `NVFuserTest`. I'm a little worried that this might interfere how other tests running in parallel....
> 
> https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Context.cpp#L35 We should probably change this to a thread_local instead....

Ah, OK, I didn't think about parallel tests. Makes sense.

**Comment by naoyam** [comment]
Well, if it's a global setting, wouldn't it be possible this change could potentially interfere with other concurrently running tests? It seems highly unlikely but if there were other tests running simultaneous using CUDNN, the change of the setting would affect those tests as well, right?

**Comment by jjsjann123** [comment]
> Well, if it's a global setting, wouldn't it be possible this change could potentially interfere with other concurrently running tests? It seems highly unlikely but if there were other tests running simultaneous using CUDNN, the change of the setting would affect those tests as well, right?

Yes. If we swap the flag, any other tests running in parallel would be affected. That's sorta the reason I don't want to spill it everywhere.

Back to the topic of changing it to a `thread_local`, I'm not sure if backward runs within the same thread, so they might have a good reason to keep it in static storage.

**Comment by naoyam** [comment]
So, there's no completely safe way to disable TF32 just for this test? If so, it seems we can't reliably use `at::conv2d` for verification.

**Comment by jjsjann123** [comment]
> So, there's no completely safe way to disable TF32 just for this test? If so, it seems we can't reliably use `at::conv2d` for verification.

If we just want some verification without spending much effort, we can keep using aten. There might be places here and there that we need to work around, but I don't see this as a deal breaker.

We can promote math type on reference ops so we see less numerical issues. Unless we implement references ourselves, it's hard to predict what other libraries would deliver.

**Comment by jjsjann123** [comment]
I'm merging this one as-is. trying to get upstream/master tests into good state, so I'm trying to get an upstream bump ready.

Will follow up on the disabling tf32 for other cpp tests. If we absolutely needed that, we can add a thread_local knob to turn off tf32 along with the global one.

**Pull request merged**
