### PR TITLE
Reuse broadcast if found when translating welford

### PR DESCRIPTION
**Pull request by naoyam**
This is to avoid broadcasting the average output of a welford op multiple times. It happens with the normalization composite op:

https://github.com/csarofeen/pytorch/blob/20_12_3_devel/torch/csrc/jit/codegen/cuda/ops/normalization.cpp#L100-L101

Here's one such example: https://gitlab-master.nvidia.com/nmaruyama/register-pressure/-/blob/master/layernorm3.cu#L3150-3160

```
broadcast::blockBroadcast<true, false, false>(
    T27[0],
    T13[0],
    static_cast<float*>(shared_mem),
    true);
  float T15[1];
  broadcast::blockBroadcast<true, false, false>(
    T15[0],
    T13[0],
    static_cast<float*>(shared_mem),
    true);
```

The second broadcast is the one created in the Welford composite op. The first one is created during the translation of the Welford op.

With this PR, the first one is not created but is substituted with `T15`.

### CODE REVIEW

**Review by shmsong — APPROVED** [review]
LGTM. One minor question: do we need to check if the broadcast to reuse concretize to the same sizes?

**Comment by jjsjann123** [comment]
> LGTM. One minor question: do we need to check if the broadcast to reuse concretize to the same sizes?

This does seem like a valid concern.
In existing use cases of welford in normalization, I think we are safe. But there's nothing stops us from broadcasting the reduced tensor to a different size.

I'm wondering what happens in that case, would that trigger a scheduler error that would eventually lead to a legit segmentation?

**Comment by naoyam** [comment]
That's a good point indeed. I didn't think about it.

If that happens, computeAt may fail since such a broadcast axis can't be shared by multiple tensors with different sizes. Such a case is *supposed* to be detected by `ComputeAtRootDomainMap`, so we should at least get an exception rather than a silent error.

Since the concern doesn't seem to be relevant for this particular case, I think we should be fine. If we get the exception, we should make this more restricted or just revert.

**Comment by jjsjann123** [comment]
:shipit:

**Pull request merged**
