### PR TITLE
Do not segment UnaryOps from fusion inputs

### LINKED ISSUE #2351: UnaryOp-only exprs from fusion inputs should not be segmented
See https://github.com/csarofeen/pytorch/issues/2348#issuecomment-1400439748

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #2351 

Tests are green. Will check performance impact.

### CODE REVIEW

**Comment by naoyam** [comment]
Overall bandwidth-speedup plots. Perf taken on the PyTorch A100 partition of dlcluster. `old` is the base commit of this PR (https://github.com/csarofeen/pytorch/tree/fix_segmentation_welford_translation). Higher speedups show perf improvements by this PR.

image

Speedup histogram:

image

There are some small number of regressions. Will look into if they are real regressions.

**Comment by naoyam** [comment]
I didn't find anything suspicious that seemed more than random noises with anything taking more than 30us. 

Here are some of the positive cases:


```
                          name	bw_base	bw_new	bw_new/bw_base
1115	NvFuserScheduler_LayerNorm_BWD_fp16___GRAPH/NvFuserScheduler_LayerNorm_BWD_fp16/160/32768/manual_time	2.962700e+11	4.030720e+11	1.360489
1125	NvFuserScheduler_LayerNorm_BWD_fp16___GRAPH/NvFuserScheduler_LayerNorm_BWD_fp16/16/262144/manual_time	3.048940e+11	4.133850e+11	1.355832
1380	NvFuserScheduler_Softmax_Outer_fp16___GRAPH/NvFuserScheduler_Softmax_Outer_fp16/4096/4096/manual_time	3.477210e+11	4.561670e+11	1.311876
1384	NvFuserScheduler_Softmax_Outer_fp16___GRAPH/NvFuserScheduler_Softmax_Outer_fp16/4096/16384/manual_time	3.799460e+11	5.438670e+11	1.431432
1155	NvFuserScheduler_LayerNorm_BWD_fp16___GRAPH/NvFuserScheduler_LayerNorm_BWD_fp16/4096/4096/manual_time	4.700980e+11	6.274340e+11	1.334688
```

In `NvFuserScheduler_LayerNorm_BWD_fp16/160/32768` with the current devel, I see that an input tensor is used in the first segment and is then saved to a temporary gmem buffer, which is then used by the next segment.  That is because the first use is not shared between the two segments, and that seems to explain the speedup.

**Review by csarofeen — APPROVED** [review]
LGTM Thanks for checking the perf. CC @liqiangxl as it could impact general normalization perf.

**Comment by liqiangxl** [comment]
> In `NvFuserScheduler_LayerNorm_BWD_fp16/160/32768` with the current devel, I see that an input tensor is used in the first segment and is then saved to a temporary gmem buffer, which is then used by the next segment. That is because the first use is not shared between the two segments, and that seems to explain the speedup.

I believe this is what I reported in last week's meeting where we have a useless gmem read-write for grad_input (dy). It is removed in the generated code after this fix.

**Pull request merged**
