### PR TITLE
[PROTOTYPE] Multidevice runtime - step 2

### PR DESCRIPTION
**Pull request by csarofeen**

### CODE REVIEW

**Comment by csarofeen** [comment]
@samnordmann please let me know if this builds correctly for you

**Comment by samnordmann** [comment]
Thanks
For now I'm getting this error when I build


```
[ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/lazy/generated/RegisterLazy.cpp.o
/.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp: In function ‘torch::jit::Operation torch::jit::createLlgaKernel(const torch::jit::Node*)’:
/.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:106:3: warning: ‘torch::jit::Operation::Operation(F&&) [with F = torch::jit::createLlgaKernel(const torch::jit::Node*)::<lambda(torch::jit::Stack*)>; typename std::enable_if<std::is_constructible<std::function<void(std::vector<c10::IValue>*)>, F&&>::value, int>::type <anonymous> = 0]’ is deprecated: Please use void(Stack&) to register operator instead. [-Wdeprecated-declarations]
  106 |   };
      |   ^
In file included from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/boxing/KernelFunction.h:5,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/dispatch/Dispatcher.h:4,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/runtime/operator.h:6,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/ir/ir.h:7,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/decompose_silu.h:3,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:2:
/.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/stack.h:25:3: note: declared here
   25 |   Operation(F&& raw): op_([raw = std::forward<F>(raw)](Stack& stack) {
      |   ^~~~~~~~~
/.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp: In function ‘torch::jit::Operation torch::jit::createLlgaGuardKernel(const torch::jit::Node*)’:
/.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:171:3: warning: ‘torch::jit::Operation::Operation(F&&) [with F = torch::jit::createLlgaGuardKernel(const torch::jit::Node*)::<lambda(torch::jit::Stack*)>; typename std::enable_if<std::is_constructible<std::function<void(std::vector<c10::IValue>*)>, F&&>::value, int>::type <anonymous> = 0]’ is deprecated: Please use void(Stack&) to register operator instead. [-Wdeprecated-declarations]
  171 |   };
      |   ^
In file included from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/boxing/KernelFunction.h:5,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/dispatch/Dispatcher.h:4,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/runtime/operator.h:6,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/ir/ir.h:7,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/decompose_silu.h:3,
                 from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:2:
/.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/stack.h:25:3: note: declared here
   25 |   Operation(F&& raw): op_([raw = std::forward<F>(raw)](Stack& stack) {
      |   ^~~~~~~~~
/.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/graph_helper.cpp: In member function ‘torch::jit::fuser::onednn::Operator torch::jit::fuser::onednn::LlgaGraphHelper::createOperator(torch::jit::Node*)’:
/.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/graph_helper.cpp:190:40: error: ‘LeakyReLU’ is not a member of ‘torch::jit::fuser::onednn::opkind’ {aka ‘dnnl::graph::op::kind’}
  190 |     return makeEltwiseOp(node, opkind::LeakyReLU)
      |                                        ^~~~~~~~~
[ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/anomaly_mode.cpp.o
[ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/autograd.cpp.o
[ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/autograd_meta.cpp.o
[ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/autograd_not_implemented_fallback.cpp.o
gmake[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/codegen/onednn/graph_helper.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
gmake: *** [all] Error 2

```

**Comment by naoyam** [comment]
> Thanks For now I'm getting this error when I build
> 
> ```
> [ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/lazy/generated/RegisterLazy.cpp.o
> /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp: In function ‘torch::jit::Operation torch::jit::createLlgaKernel(const torch::jit::Node*)’:
> /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:106:3: warning: ‘torch::jit::Operation::Operation(F&&) [with F = torch::jit::createLlgaKernel(const torch::jit::Node*)::<lambda(torch::jit::Stack*)>; typename std::enable_if<std::is_constructible<std::function<void(std::vector<c10::IValue>*)>, F&&>::value, int>::type <anonymous> = 0]’ is deprecated: Please use void(Stack&) to register operator instead. [-Wdeprecated-declarations]
>   106 |   };
>       |   ^
> In file included from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/boxing/KernelFunction.h:5,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/dispatch/Dispatcher.h:4,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/runtime/operator.h:6,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/ir/ir.h:7,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/decompose_silu.h:3,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:2:
> /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/stack.h:25:3: note: declared here
>    25 |   Operation(F&& raw): op_([raw = std::forward<F>(raw)](Stack& stack) {
>       |   ^~~~~~~~~
> /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp: In function ‘torch::jit::Operation torch::jit::createLlgaGuardKernel(const torch::jit::Node*)’:
> /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:171:3: warning: ‘torch::jit::Operation::Operation(F&&) [with F = torch::jit::createLlgaGuardKernel(const torch::jit::Node*)::<lambda(torch::jit::Stack*)>; typename std::enable_if<std::is_constructible<std::function<void(std::vector<c10::IValue>*)>, F&&>::value, int>::type <anonymous> = 0]’ is deprecated: Please use void(Stack&) to register operator instead. [-Wdeprecated-declarations]
>   171 |   };
>       |   ^
> In file included from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/boxing/KernelFunction.h:5,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/dispatch/Dispatcher.h:4,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/runtime/operator.h:6,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/ir/ir.h:7,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/decompose_silu.h:3,
>                  from /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/interface.cpp:2:
> /.autodirect/mtrsysgwork/snordmann/pytorch/aten/src/ATen/core/stack.h:25:3: note: declared here
>    25 |   Operation(F&& raw): op_([raw = std::forward<F>(raw)](Stack& stack) {
>       |   ^~~~~~~~~
> /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/graph_helper.cpp: In member function ‘torch::jit::fuser::onednn::Operator torch::jit::fuser::onednn::LlgaGraphHelper::createOperator(torch::jit::Node*)’:
> /.autodirect/mtrsysgwork/snordmann/pytorch/torch/csrc/jit/codegen/onednn/graph_helper.cpp:190:40: error: ‘LeakyReLU’ is not a member of ‘torch::jit::fuser::onednn::opkind’ {aka ‘dnnl::graph::op::kind’}
>   190 |     return makeEltwiseOp(node, opkind::LeakyReLU)
>       |                                        ^~~~~~~~~
> [ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/anomaly_mode.cpp.o
> [ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/autograd.cpp.o
> [ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/autograd_meta.cpp.o
> [ 78%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/autograd/autograd_not_implemented_fallback.cpp.o
> gmake[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/codegen/onednn/graph_helper.cpp.o] Error 1
> gmake[2]: *** Waiting for unfinished jobs....
> gmake[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
> gmake: *** [all] Error 2
> ```

Looks like you have a problem with oneDNN, which is a cuDNN-like library from Intel. Try `USE_MKLDNN=0` when running the build script. You may need to try from scratch.

**Comment by samnordmann** [comment]
I needed this small fix https://github.com/csarofeen/pytorch/pull/2207
Now it builds successfully!

**Review by samnordmann — APPROVED** [review]

**Comment by csarofeen** [comment]
Closed in favor of: https://github.com/csarofeen/pytorch/pull/2318

**Pull request closed without merging**
