### PR TITLE
python tests moving under nvfuser directory

### PR DESCRIPTION
**Pull request by jjsjann123**
Moving some files around (nvfuser specific python tests)
Also added a `manaul_ci.sh` to run all related tests.

### CODE REVIEW

**Comment by jjsjann123** [comment]
This one is good for review, I'm marking it as draft since there's failing test (already patched upstream, I'll cherry-pick it).

**Comment by jjsjann123** [comment]
ahhhh... git is dumb... it can't figure out that I'm moving files... I'll try to break this up in two PRs...

**Comment by jjsjann123** [comment]
split part of it into #2384. so this is an easier review.

**Review by naoyam — APPROVED** [review]

**Comment by jjsjann123** [comment]
I'll merge this one once CI passed.

**Comment by jjsjann123** [comment]
:laughing: merging the second PR into this one makes github diff exploded again. But I already got Naoya's stamp so I'm moving along with it just as-is.

The real code change should be less than a hundred... Please don't be scared.

**Pull request merged**
