### PR TITLE
switching `packaging.version.Version` to `torch.torch_version.Version`

### PR DESCRIPTION
**Pull request by jjsjann123**
1. Avoids nvfuser importing error on platforms without python `packaging`.
2. Patch on confusing error message when `./nvfuser/__init__.py` fails on consecutive imports.

### CODE REVIEW

**Comment by kevinstephano** [comment]
I was wondering why you didn't just use the Lazy Import code instead of depending on Torch in this instance?

```python
class _LazyImport:
    """Wraps around classes lazy imported from packaging.version
    Output of the function v in following snippets are identical:
       from packaging.version import Version
       def v():
           return Version('1.2.3')
    and
       Version = _LazyImport('Version')
       def v():
           return Version('1.2.3')
    The difference here is that in later example imports
    do not happen until v is called
    """
    def __init__(self, cls_name: str) -> None:
        self._cls_name = cls_name

    def get_cls(self):
        try:
            import packaging.version  # type: ignore[import]
        except ImportError:
            # If packaging isn't installed, try and use the vendored copy
            # in pkg_resources
            from pkg_resources import packaging  # type: ignore[attr-defined, no-redef]
        return getattr(packaging.version, self._cls_name)

    def __call__(self, *args, **kwargs):
        return self.get_cls()(*args, **kwargs)

    def __instancecheck__(self, obj):
        return isinstance(obj, self.get_cls())
```

**Comment by jjsjann123** [comment]
I'm doing that just to avoid duplicating code. Also, I don't understand why we need to use pkg_resources instead of just adding packaging in requirements.txt :shrug: 
We have torch accompany us so might as well just use what they have.

I can copy that code if you have strong opinion on this :stuck_out_tongue_closed_eyes:

**Comment by kevinstephano** [comment]
My preference is to limit our dependences on Pytorch where we can.  I would just copy the lazy importing code in this instance or add a requirement to use `packaging` if it isn't installed like APEX does if that is a suitable workaround.

**Comment by jjsjann123** [comment]
duplicated lazy import. I think this is the only request?! cc'ing @kevinstephano

**Review by kevinstephano — APPROVED** [review]
LGTM.

**Pull request merged**
