### PR TITLE
[WIP] Contiguous Dimension Collapsing

### PR DESCRIPTION
**Pull request by jjsjann123**

### CODE REVIEW

**Comment by jjsjann123** [comment]
This one targets #194

Currently it's only handling point-wise operation and does not support broadcast/reduction yet.

**Comment by jjsjann123** [comment]
Shelve the work since Christian is working on supporting collapsing in codegen.

**Comment by csarofeen** [comment]
@jjsjann123 can this be closed?

**Comment by jjsjann123** [comment]
Sorry missed the thread, closing.

**Pull request closed without merging**
