### PR TITLE
Use vectorize predicate for non-vectorized domains that are exactly mapped with vectorized domains

### PR DESCRIPTION
**Pull request by naoyam**
If an ID is exactly mapped with a vectorized ID, it should be valid to use the same vectorize predicate, assuming the vectorization is validated correctly.

Added a simple test to demonstrate the difference. 

Before:
```
__global__ void CUDAGeneratedKernel(Tensor<float, 1> T0, Tensor<float, 1> T2) {
  alignas(16) extern __shared__ char array[];
  unsigned smem_offset = 0;
  NVFUSER_DEFINE_MAGIC_ZERO
  smem_offset = alignBufferSize(smem_offset, 16);
  float* T1 = reinterpret_cast<float*>(array + smem_offset);
  smem_offset += (((ceilDiv(T0.size[0], 4)) * 4) * sizeof(float));
  #pragma unroll 1
  for(nvfuser_index_t i12 = 0; i12 < (ceilDiv(T0.size[0], 4)); ++i12) {
    #pragma unroll
    for(nvfuser_index_t i13 = 0; i13 < 4; ++i13) {
      int64_t i28;
      i28 = (i12 * 4) + (i13 + nvfuser_zero);
      if ((i28 < T0.size[0])) {
        T1[((i12 * 4) + i13)]
           = T0[i28];
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
  #pragma unroll 1
  for(nvfuser_index_t i14 = 0; i14 < (ceilDiv(T0.size[0], 4)); ++i14) {
    #pragma unroll
    for(nvfuser_index_t i15 = 0; i15 < 4; ++i15) {
      int64_t i58;
      i58 = (i14 * 4) + (i15 + nvfuser_zero);
      if ((i58 < T0.size[0])) {
        T2[i58]
           = T1[((i14 * 4) + i15)];
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
}
```

After:
```
__global__ void CUDAGeneratedKernel(Tensor<float, 1> T0, Tensor<float, 1> T2) {
  alignas(16) extern __shared__ char array[];
  unsigned smem_offset = 0;
  NVFUSER_DEFINE_MAGIC_ZERO
  smem_offset = alignBufferSize(smem_offset, 16);
  float* T1 = reinterpret_cast<float*>(array + smem_offset);
  smem_offset += (((ceilDiv(T0.size[0], 4)) * 4) * sizeof(float));
  #pragma unroll 1
  for(nvfuser_index_t i12 = 0; i12 < (ceilDiv(T0.size[0], 4)); ++i12) {
    int64_t i24;
    i24 = i12 * 4;
    if ((((i12 * 4) + 3) < T0.size[0])) {
      loadGeneric<float, 4>( &T1[i24],  &T0[i24]);
    }
  }
  #pragma unroll 1
  for(nvfuser_index_t i14 = 0; i14 < (ceilDiv(T0.size[0], 4)); ++i14) {
    #pragma unroll
    for(nvfuser_index_t i15 = 0; i15 < 4; ++i15) {
      if ((((i14 * 4) + 3) < T0.size[0])) {
        T2[((i14 * 4) + (i15 + nvfuser_zero))]
           = T1[((i14 * 4) + i15)];
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
}
```

The difference is the predicate of `T2`, which changes from `(i14 * 4) + (i15 + nvfuser_zero)` to `(i14 * 4) + 3`. 

This PR just replaces loop indices with `extent -1`. It's also possible to lift predicates out of innermost loops. In the above case, the predicate of `T2` can be placed outside of the `i15` loop. This should be extremely trivial compiler optimization if it's deemed profitable, so at this point I kept it unchanged. Will revisit if found necessary to do ourselves.

This optimization is not specific to vectorization. I think that we should be able to apply the same optimization for any leaf ID whose splits are all divisible. I'm not sure how often we would see all divisible splits, though. Will also revisit if necessary.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Looks like in the for loop of `i15`, the code changed from
```C++
      i58 = (i14 * 4) + (i15 + nvfuser_zero);
      if ((i58 < T0.size[0])) {
        T2[i58]
           = T1[((i14 * 4) + i15)];
      }
```
to
```C++
      if ((((i14 * 4) + 3) < T0.size[0])) {
        T2[((i14 * 4) + (i15 + nvfuser_zero))]
           = T1[((i14 * 4) + i15)];
      }
```
what would happen if `T0.size[0]` is not a multiple of 4, for example, `T0.size[0] == 6`? Will there be something missing, since  if `i14` is 1, then the predicate `(i14 * 4) + 3) < T0.size[0]` will not satisfy, even if `i15` can be 0 or 1?

**Comment by zasdfgbnm** [comment]
So, we only vectorize 4 only if the tensor's number of elements is a multiple of 4? So if a tensor has 6 elements, we will do vec2 * 3, instead of vec4 + vec2?

**Comment by naoyam** [comment]
Yeah, if a domain is vectorized by 4, its extent must be divisible by 4. There should be a runtime check of the divisibility.

If a domain extent is 6, I'm not sure if we can do vec2 + vec4.

**Comment by csarofeen** [comment]
Does https://github.com/csarofeen/pytorch/pull/1970 not already remove the predicates you're targeting as it adds vectorized splits to the divisible split map which is used to omit predicates?

**Comment by naoyam** [comment]
> Does #1970 not already remove the predicates you're targeting as it adds vectorized splits to the divisible split map which is used to omit predicates?

Currently, no, it doesn't, but it's an actually a good point. For example:

```
t0: [I1]
t1 = t0

t0->split(0, 4)
t1->split(0, 4)

t0->axis(1)->parallelize(ParallelType::Vectorize)
```

In this case, the default way of predicating `t1` is like `i * 4 + j < I1`, but with this PR, it would be `i * 4 + 3 < I1`. The fact that `I1` is divisible by 4 does not necessarily mean we don't need to predicate `t1` at all. Specifically, in this case, if `i` is guaranteed to be less than `I1 / 4`, we can omit the `t1` predicate completely. We don't guarantee that condition as `t1` can be further split and the split can be non-divisible. We could extend the analysis and try to omit predicates more aggressively, but I'm not so confident if it could give us a meaningful difference as it would only matter if everything is guaranteed to be divisible.

**Comment by naoyam** [comment]
I should have mentioned I'm updating this PR using the divisible split set.

**Comment by naoyam** [comment]
Updated to use `GpuLower::divisibleSplitSet`. Ready for review again.

**Review by csarofeen — APPROVED** [review]
LGTM

**Pull request merged**
