### PR TITLE
avoid promote float16 and bfloat16 to float32 in op-where

### LINKED ISSUE #2378: Python where op promotes float16 and bfloat16 to float32
```
pred = make_tensor((5,), device='cuda', dtype=torch.bool)
a = torch.randn((5,), device='cuda', dtype=torch.float16)
b = torch.randn((5,), device='cuda', dtype=torch.float16)

fs = Fusion()
with FusionDefinition(fs) as fd:
    nv_pred = fd.define_tensor(sizes=pred.shape, strides=pred.stride(), dtype=DataType.Bool)
    nv_a = fd.define_tensor(sizes=a.shape, strides=a.stride(), dtype=DataType.Half)
    nv_b = fd.define_tensor(sizes=b.shape, strides=b.stride(), dtype=DataType.Half)

    result = fd.ops.where(nv_pred, nv_a, nv_b)

    fd.add_output(result)

nv_result = fs.execute((pred, a, b))[0]

print(f"nv_result={nv_result}")
: nv_result=tensor([-0.9683, -1.1797,  0.2546, -0.6099,  2.0898], device='cuda:0')
```

Compare to PyTorch:

```
torch_result = torch.where(pred, a, b)
print(f"torch_result={torch_result}")
: torch_result=tensor([-0.9683, -1.1797,  0.2546, -0.6099,  2.0898], device='cuda:0',
       dtype=torch.float16)
```

### PR DESCRIPTION
**Pull request by liqiangxl**
Fixes #2378 
if two inputs are both float16 will return float16.
if two inputs are both bfloat16 will return bfloat16.
if one is float16 or bfloat16, the other one is float32, will return float32.

Do we have a folder to place python unit test?
```
import torch
from nvfuser import FusionDefinition, DataType
from nvfuser.pytorch_utils import torch_dtype_to_nvfuser_dtype

pred = torch.testing.make_tensor((5,), device='cuda', dtype=torch.bool)

def nvfuser_where(a, b):
    with FusionDefinition() as fd:
        nv_pred = fd.define_tensor(sizes=pred.shape, strides=pred.stride(), dtype=DataType.Bool)
        nv_a = fd.define_tensor(sizes=a.shape, strides=a.stride(), dtype=torch_dtype_to_nvfuser_dtype(a.dtype))
        nv_b = fd.define_tensor(sizes=b.shape, strides=b.stride(), dtype=torch_dtype_to_nvfuser_dtype(b.dtype))

        result = fd.ops.where(nv_pred, nv_a, nv_b)

        fd.add_output(result)

    return fd.execute((pred, a, b))[0]
    
def test(a,b):
    nv_result = nvfuser_where(a, b)
    torch_result = torch.where(pred, a, b)
    torch.testing.assert_close(nv_result, torch_result)

list_of_dtype = [torch.float16, torch.bfloat16, torch.float32]
for atype in list_of_dtype:
    for btype in list_of_dtype:
        a = torch.randn((5,), device='cuda', dtype=atype)
        b = torch.randn((5,), device='cuda', dtype=btype)
        test(a,b)
```

### CODE REVIEW

**Comment by kevinstephano** [comment]
Yes we do have a directory for Python tests.  They can be added at `third_party/nvfuser/python_tests/test_python_frontend.py`

**Comment by kevinstephano** [comment]
Looks good so far, just add a test or two.

**Comment by liqiangxl** [comment]
> Looks good so far, just add a test or two.

added.

**Review by jjsjann123 — APPROVED** [review]
LGTM.

**Review by kevinstephano — APPROVED** [review]
LGTM!

**Pull request merged**
