### PR TITLE
Remove debugging `true ||` from getPointwiseHeuristics

### PR DESCRIPTION
**Pull request by zasdfgbnm**
I am seeing a
```c++
if (true || 
```
in the code, was this used for debugging and forgotten to remove?

### CODE REVIEW

**Review by naoyam — APPROVED** [review]

**Comment by naoyam** [comment]
Wait, maybe it was intended to disable the fallback to the 1D scheduler?

**Comment by zasdfgbnm** [comment]
I don't know /shrug. @csarofeen Do you know why we have this?

**Comment by csarofeen** [comment]
Was definitely debugging code, but need to go check it doesn't cause regressions to take it out.

**Comment by csarofeen** [comment]
Even when I change the multiplier to 2 for the benchmarking of broadcast there's only a couple dozen of these cases and it seems to make no difference if they're 1D or 2D scheduled, so you can remove the true or it seems safe to just always go through the 2D scheduler logic to see if there's a 2D way to schedule it.

**Pull request merged**
