### PR TITLE
Add parsing support for `_to_copy` to handle AMP casts.

### PR DESCRIPTION
**Pull request by kevinstephano**
Fix amp casting.

### CODE REVIEW

**Comment by csarofeen** [comment]
@kevinstephano looks like this needs to be rebased after updating master.

**Comment by csarofeen** [comment]
@kevinstephano @jjsjann123 can we get this cleaned up, reviewed, and merged please?

**Comment by jjsjann123** [comment]
Lol, sorry I totally forgot this one.

**Review by jjsjann123 — APPROVED** [review]
stamping my own code change :speak_no_evil:

**Pull request merged**
