### PR TITLE
Replace Static_Cast with As

### LINKED ISSUE #187: Clean up static_cast in favor of as
We still have a lot of code that uses `static_cast` to convert between node types i.e. `Val*`->`TensorView*`. We should change all of these to use `::as<NodeType>()`.

### PR DESCRIPTION
**Pull request by rdspring1**
Resolve Issue #187

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
LGTM. Most (all?) of the `as<const XYZ>` can be replaced with just `as<XYZ>`.

**Comment by tlemo** [comment]
> Most (all?) of the `as<const XYZ>` can be replaced with just `as<XYZ>`.

Good catch @naoyam. Yes, another nice benefit of as<> is that you don't need to explicitly request `const T` in most cases ( unless you have a non-const and you want to produce a const variant)

**Comment by tlemo** [comment]
@rdspring1 : as<> also provides runtime checking in DEBUG builds, so it's worth running our tests with a DEBUG build if you haven't already done so (or I can do this for you if you want)

**Comment by rdspring1** [comment]
I ran the DEBUG build and the tests pass. I also removed the const.

**Pull request merged**
