### PR TITLE
[View] Avoid updating extent in IndexCompute::handle(Split* split)

### PR DESCRIPTION
**Pull request by rdspring1**
### Problem:
In the case of view, updating the extent when handling a split in `IndexCompute` can cause inconsistent indexing.

https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/index_compute.cpp#L614-L620

### Proposed Solution: 
Avoid updating extent if `split->in()->definition() != nullptr` and `split` is marked as `viewSplit`.

### Alternate Solution:
Avoid updating extent at all if 'split->in()->definition() != nullptr'.

**Coalesced Memory Access Concern:**
For example, assuming blockDim.x is 128, gridDim.x is some value, and given a single-dimension tensor t0 to load t0 in a coalesced manner, we could do:
```
// t0: [I]
t0->split(0, BIDX, false); 
t0->split(1, TIDX);
// t0: [BIDX, ceilDiv(ceilDiv(I, BIDX), TIDX), TIDX] 
```
In this case, currently, we generate `t0` index as: `blockIdx.x * ceilDiv(ceilDiv(I, gridDim.x), blockDim.x) * blockDim.x + j * blockDim.x + threadIdx.x `, which should result in nicely coalesced accesses (assuming the `t0` allocation is aligned properly).

With this change, however, it would be: `blockIdx.x * ceilDiv(I, gridDim.x) + j * blockDim.x + threadIdx.x` . Since `ceilDiv(I, gridDim.x)` may not be a multiple of any coalesced access size, it would result in non-coalesced accesses.
I'm not sure how much we should worried about this. We could do instead:
```
t0->split(0, BIDX*TIDX);
t0->split(1, TIDX);
// t0: [ceilDiv(I, BIDX*TIDX), BIDX, TIDX]
```
Then, this would be always coalesced.

### CODE REVIEW

**Comment by rdspring1** [comment]
Failing View fusion example:
```
void geluViewAddFusion(
    std::vector<int64_t> input_shape,
    std::vector<int64_t> output_shape) {
  for (auto hasImplicitBroadcast : {false, true}) {
    Fusion fusion;
    FusionGuard fg(&fusion);

    TensorView* x = (hasImplicitBroadcast)
        ? makeConcreteTensor(input_shape)
        : makeSymbolicTensor(input_shape.size());
    TensorView* bias = (hasImplicitBroadcast)
        ? makeConcreteTensor(output_shape)
        : makeSymbolicTensor(output_shape.size());
    fusion.addInput(x);
    fusion.addInput(bias);

    auto x_gelu = unaryOp(UnaryOpType::Gelu, x);
    auto x_view = view(x_gelu, input_shape, output_shape);
    auto y = add(bias, x_view);
    fusion.addOutput(y);

    auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
    at::Tensor at_x = at::randn(input_shape, options);
    at::Tensor at_bias = at::randn(output_shape, options);
    std::vector<IValue> aten_inputs = {at_x, at_bias};

    auto lparams = schedulePointwise(&fusion, aten_inputs);

    fusion.printKernel();

    FusionExecutor fe;
    fe.compileFusion(&fusion);
    auto outputs = fe.runFusion(aten_inputs, lparams);

    auto at_x_gelu = at::gelu(at_x, false);
    auto at_x_view = at::native::view(at_x_gelu, output_shape);
    auto at_y = at_x_view + at_bias;

    testValidate(&fusion, outputs, aten_inputs, {at_y}, __LINE__, __FILE__);
  }
}

TEST(NVFuserTest, FusionViewStride_CUDA) {
  geluViewAddFusion({1, 27454, 2}, {1, 7844, 7});
}
```

**Comment by rdspring1** [comment]
Failing Index:
```
T5[ki427]
  = T0[((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * 1) + ki400) / 7844) * T0.stride[0]) +
  (((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * 1) + ki400) % 7844) * (((ceilDiv((ceilDiv((ceilDiv((T0.size[1] * T0.size[2]), 7844)), ((nvfuser_index_t)blockDim.x))), 4)) * 4) * ((nvfuser_index_t)blockDim.x))) + ((((ki392 * 4) + (ki427 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x))) / T0.size[2]) * T0.stride[1]) + 
  (((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * 1) + ki400) % 7844) * (((ceilDiv((ceilDiv((ceilDiv((T0.size[1] * T0.size[2]), 7844)), ((nvfuser_index_t)blockDim.x))), 4)) * 4) * ((nvfuser_index_t)blockDim.x))) + ((((ki392 * 4) + (ki427 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x))) % T0.size[2]) * T0.stride[2])];
```
Updated extent:
`(((ceilDiv((ceilDiv((ceilDiv((T0.size[1] * T0.size[2]), 7844)), ((nvfuser_index_t)blockDim.x))), 4)) * 4)`

Passing index:
```
T5[ki427]
  = T0[((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * 1) + ki400) / 7844) * T0.stride[0]) +
  (((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * 1) + ki400) % 7844) * (ceilDiv((T0.size[1] * T0.size[2]), 7844))) + ((((ki392 * 4) + (ki427 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x))) / T0.size[2]) * T0.stride[1]) +
  (((((((((((nvfuser_index_t)blockIdx.x) * ((nvfuser_index_t)blockDim.y)) + ((nvfuser_index_t)threadIdx.y)) * 1) + ki400) % 7844) * (ceilDiv((T0.size[1] * T0.size[2]), 7844))) + ((((ki392 * 4) + (ki427 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x))) % T0.size[2]) * T0.stride[2])];
```
Unchanged extent:
`(ceilDiv((T0.size[1] * T0.size[2]), 7844)))`

**Comment by naoyam** [comment]
First of all, the current way of updating the extent map does not work with `view`.

https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/index_compute.cpp#L614-L620

The question is when the extent of the input IterDomain of a split should be updated by the multiplication of the output domain extents. If it has `zero_merged_in`, the original extent of the split input is no longer valid, so it should be updated. Otherwise, it updates the extent map within each root domain. This makes sense as we predicate each root domain.

However, with `view`, a root domain of a tensor after a `view` operation may be an intermediate domain of a tensor before the `view` operation, so if they are used together, the indexing can be inconsistent due to the different extents.

The inconsistency is caused by the fact that there's a domain being considered as a root domain and another mapped domain being considered as an intermediate domain. Thus, a simple fix is to stop updating the extent mapping for split input domains except for the zero-merged case. This way, both tensors before and after view would be consistently indexed. This is the alternate solution Ryan refers to.

However, this could affect indexing of potentially many kernels. Effectively, if a non-root domain is split non-evenly, the resulting index would be different. I'm not completely sure what performance implication it would have, but one hypothetical concern is the failure to do coalescing in some cases like the one mentioned above. Specifically, currently, `t0` would be indexed as:

```
t0[blockIdx.x * ceilDiv(ceilDiv(I, gridDim.x), blockDim.x) * blockDim.x + j * blockDim.x + threadIdx.x]
```

With the fix, it would be indexed as:

```
t0[blockIdx.x * ceilDiv(I, gridDim.x) + j * blockDim.x + threadIdx.x]
```

While the latter index expression looks simpler, it does not guarantee coalesced accesses since `ceilDiv(I, gridDim.x)` may not be a multiple of a coalescing chunk size. In the former case, as long as `blockDim.x` is a multiple of the coalescing chunk size (and `t0` allocation is aligned), it should be always coalesced.

Ryan's fix implemented in this PR tries to minimize the impact of the indexing change. It keeps the current way of updating the extent map for the input domain of a split expression, only if the split is not used for a `view` operation. I need to look at the code more closely, but the idea is to limit the impact of the indexing change to those cases where `view` is used. 

Personally, I'd prefer just avoiding updating the extent map (i.e., the alternate solution) as the logic is much simpler, but if it actually causes non-negligible performance regressions, this PR's approach would be more preferable.

**Comment by rdspring1** [comment]
Closed in favor of #1270

**Pull request closed without merging**
