### PR TITLE
Add support for NVTX tracing

### PR DESCRIPTION
**Pull request by tlemo**
This PR adds NVTX markers to the built-in instrumentation

### CODE REVIEW

**Review by kevinstephano — APPROVED** [review]
LGTM

**Review by jjsjann123 — COMMENTED** [review]
IIUC, the added nvtx range is not controlled by the knob we use to turn on/off tracing.

Can we also put a knob for nvtx as well?

**Comment by tlemo** [comment]
> IIUC, the added nvtx range is not controlled by the knob we use to turn on/off tracing.
> 
> Can we also put a knob for nvtx as well?

This is intentional. NVTX has close to zero overhead unless it's attached to an application. So there is a knob, but it's controlled through the NVTX, not by us.

**Comment by jjsjann123** [comment]
I'm less worried about overhead, more about distraction in profile. We can have people profiling their model with nvtx using our fuser. Admittedly this is a minor convenience thing.

**Pull request merged**
