### PR TITLE
fixing MSVC build

### PR DESCRIPTION
**Pull request by jjsjann123**
cherry-picked from https://github.com/pytorch/pytorch/pull/77471

### CODE REVIEW

**Review by naoyam — APPROVED** [review]
Thanks for the fix. No idea why this didn't work with MSVC, but 🤷

**Comment by jjsjann123** [comment]
> Thanks for the fix. No idea why this didn't work with MSVC, but shrug

Since you asked:

```
runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\test\test_gpu_fused_reduction.cpp
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\test\test_gpu_fused_reduction.cpp(1230): error C3493: 'channels_last' cannot be implicitly captured because no default capture mode has been specified
```

https://github.com/pytorch/pytorch/runs/6475265281?check_suite_focus=true

**Comment by naoyam** [comment]
> > Thanks for the fix. No idea why this didn't work with MSVC, but shrug
> 
> Since you asked:
> 
> ```
> runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\test\test_gpu_fused_reduction.cpp
> C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\test\test_gpu_fused_reduction.cpp(1230): error C3493: 'channels_last' cannot be implicitly captured because no default capture mode has been specified
> ```
> 
> https://github.com/pytorch/pytorch/runs/6475265281?check_suite_focus=true

But, I thought that should be automatically captured: 

```
A lambda expression can read the value of a variable without capturing it if the variable
 has const non-volatile integral or enumeration type and has been initialized with a constant expression
```
https://en.cppreference.com/w/cpp/language/lambda

**Comment by jjsjann123** [comment]
> > > Thanks for the fix. No idea why this didn't work with MSVC, but shrug
> > 
> > 
> > Since you asked:
> > ```
> > runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\test\test_gpu_fused_reduction.cpp
> > C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\test\test_gpu_fused_reduction.cpp(1230): error C3493: 'channels_last' cannot be implicitly captured because no default capture mode has been specified
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/pytorch/pytorch/runs/6475265281?check_suite_focus=true
> 
> But, I thought that should be automatically captured:
> 
> ```
> A lambda expression can read the value of a variable without capturing it if the variable
>  has const non-volatile integral or enumeration type and has been initialized with a constant expression
> ```
> 
> https://en.cppreference.com/w/cpp/language/lambda

You are perfectly right about this and it should also explain why it never fails for our gcc/clang build. But we should never hold MSVC to be on the same standard :stuck_out_tongue_winking_eye: 
https://developercommunity.visualstudio.com/t/lambda-fails-to-implicitly-capture-constexpr-value/610504

I'll add a link to that bug in the comment

**Comment by jjsjann123** [comment]
Have to give them the credit that it's fixed.. Guess upstream is not on the updated MSVC toolkit.

**Pull request merged**
