### PR TITLE
Rename view to reshape (redo)

### PR DESCRIPTION
**Pull request by kevinstephano**
Renaming view as reshape since nvFuser's implementation is considered reshape to remove confusion.

I messed up the merge in my previous PR #2377

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
LGTM. What branch are you trying to roll these changes up into?

**Comment by kevinstephano** [comment]
This PR, in particular, did not need to roll into another branch besides `devel`.  I had a couple of `FusionDefinition` PRs that were dependent on each other and I made this dependent on the last one I made for no good reason.  I think I was just on autopilot when I made the first PR I needed to redo.

**Comment by csarofeen** [comment]
If you want to redirect it to devel we can merge it in

**Comment by kevinstephano** [comment]
Ugh, I think I made a mess by creating this as branch of a branch.  When I make a PR to devel directly it includes changes from the branch that is not merged yet as it hasn't been approved.

**Comment by csarofeen** [comment]
Third time's the charm? ;-)

**Comment by kevinstephano** [comment]
> Third time's the charm? ;-)

Yeah, sorry for the approval churn. :-(

**Comment by csarofeen** [comment]
NBD

**Comment by kevinstephano** [comment]
Closing in a favor of a PR directly to the `devel` branch.

**Pull request closed without merging**
