### PR TITLE
Don't exact map across data swizzles.

### PR DESCRIPTION
**Pull request by csarofeen**
I don't think it makes any sense to exact map across data swizzles as they cannot share the same indexing by definition. We could add an exception for a null swizzle. *Loop* swizzles on the other hand only change iteration order, their indexing is the same, they can be exact mapped.

### CODE REVIEW

**Comment by naoyam** [comment]
> I don't think it makes any sense to exact map across data swizzles as they cannot share the same indexing by definition. We could add an exception for a null swizzle. Data swizzles on the other hand only change iteration order, their indexing is the same, they can be exact mapped.

I believe you meant "Loop swizzles on the other hand..."

**Comment by csarofeen** [comment]
Yes, thanks.

**Review by naoyam — APPROVED** [review]
Makes sense to me

**Comment by zasdfgbnm** [comment]
This makes sense to me as well. Just leaving a side note here: Looks like the current design of swizzle does not fit the transpose scheduler very well. The transpose scheduler schedules tensor like this:
```
T0_s[Outer, Inner]

split and reorder:
T0_s[Outer/OuterTile, Inner/InnerTile, OuterTile, InnerTile]

vectorize:
T0_s[Outer/OuterTile, Inner/InnerTile, OuterTile, InnerTile/V, V]

merge and parallelize
T0_s[BIDx{Outer/OuterTile*Inner/InnerTile}, TIDx{OuterTile*InnerTile/V}, V]
```
The best place to apply swizzle to me is after `vectorize` and before `merge and parallelize` and swizzle the dimension `OuterTile` and `InnerTile/V`. But this would mean the output of swizzle is no longer a leaf, which is not supported by the current implementation. We should not prioritize adding swizzle+transpose support, but it would be a good opportunity to consider this if we rewrite indexing.

**Review by zasdfgbnm — APPROVED** [review]

**Comment by csarofeen** [comment]
I'm in full agreement, and we've always intended to work towards swizzle support that's not necessarily on the leaves. Definitely seems we have a ways to go, but will be great when we can get there ;-)

**Pull request merged**
