### PR TITLE
empty gpu memory cache between different benchmark cases (#2242)

### LINKED ISSUE #2242: 10% difference in benckmark results of different runs with different number of cases
### 🐛 Describe the bug

test the benchmark of layer_norm with 7 cases using `./bin/nvfuser_bench --benchmark_filter=NvFuserScheduler_LayerNorm_fp32`
```
NVFUSER_BENCHMARK_RUN(NvFuserScheduler_LayerNorm_fp32)
    ->RangeMultiplier(2)
    ->Ranges({{2048, 2048}, {1024, 1024 * 32}})
    ->Unit(benchmark::kMicrosecond)
    ->UseManualTime();
NVFUSER_BENCHMARK_RUN(NvFuserScheduler_LayerNorm_fp32)
    //->RangeMultiplier(2)
    ->Ranges({{2048, 2048}, {20480, 20480}})
    ->Unit(benchmark::kMicrosecond)
    ->UseManualTime();
```
The bandwidth for the last case is 1067 GB/s.
Then just benckmark the last case with:
```
/* comment out first 6 cases to just run the 7th case.
NVFUSER_BENCHMARK_RUN(NvFuserScheduler_LayerNorm_fp32)
    ->RangeMultiplier(2)
    ->Ranges({{2048, 2048}, {1024, 1024 * 32}})
    ->Unit(benchmark::kMicrosecond)
    ->UseManualTime(); */
NVFUSER_BENCHMARK_RUN(NvFuserScheduler_LayerNorm_fp32)
    //->RangeMultiplier(2)
    ->Ranges({{2048, 2048}, {20480, 20480}})
    ->Unit(benchmark::kMicrosecond)
    ->UseManualTime();
```
The bandwidth changed to 1.178 TB/s (13% faster than testing 7 cases)

### Versions

devel

### PR DESCRIPTION
**Pull request by liqiangxl**
Fixes #2242
(1) Reason: PyTorch uses a caching memory allocator to speed up memory allocations. Testing multi-cases in a single run lead to less avilable gpu memroy for the last case and more allocated gpu memory pieces in the memory pool. It may take longer to find the appropriate piece of memory.
(2) Fix: clear memory pool.
(3) Results: after fix the performance difference reduced from 13% to 1%.
Before fix: run 7 cases the performance of last case is: 1.042 TB/s (1067/1024)
After    fix: run 7 cases the performance of last case is: 1.190 TB/s
run only the last case: 1.178 TB/s

### CODE REVIEW

**Comment by csarofeen** [comment]
I was just having a conversation with someone recently about how we profile results, specifically if we're concerned about how performance can change under the full workload versus isolated benchmarks. Might have been with @drzejan2 this is a pretty interesting example where even the allocator can interfere. The caching allocator has worked really well for us for a long time, but might be time for us to start placing allocations more carefully, in real workloads.

I'm fine with the change, just an interesting concrete example of concerns that are often hand-wavy.

**Comment by naoyam** [comment]
That's a nice catch, @liqiangxl! I thought we didn't include memory allocations in the measurement.

**Review by naoyam — APPROVED** [review]
LGTM

**Comment by drzejan2** [comment]
@csarofeen thanks for letting me know about this fix.
I haven't moved to the benchmark infrastructure in the project but I plan to start moving in that direction really soon - for the time being I will rely on simple sample and CUDA events from its execution.

**Pull request merged**
