### PR TITLE
Quick fix on serial shared mem writes

### PR DESCRIPTION
**Pull request by shmsong**
It looks like we are missing a block sync in the case when the shared mem is serially written and parallel read, see repro `FusionSeriaSmemlWriteParallelRead`. 

This PR is the quick fix that should be minimally different from original behavior.

### CODE REVIEW

**Comment by naoyam** [comment]
Nice catch!

Can this be done using the redundant type information that `ThreadPredicateMap` has?

```
auto redundant_preds = GpuLower::current()
                                     ->threadPredMap()
                                     .getPredicateInfo(producer)
                                     .redundant_types;
```

**Comment by naoyam** [comment]
The redundant type information captures tensors that are predicated with, e.g., `threadIdx.x == 0`, so if a producer has a redundant parallel type, and that type is used by the consumer, we need a RAW sync.

**Comment by shmsong** [comment]
> The redundant type information captures tensors that are predicated with, e.g., `threadIdx.x == 0`, so if a producer has a redundant parallel type, and that type is used by the consumer, we need a RAW sync.

Sure it should work either way at the current state of sync info pass.

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
