### PR TITLE
[ON HOLD] Slightly lift one constraint on parallel validate and add test for it.

### PR DESCRIPTION
**Pull request by csarofeen**
Long comment and test in PR.

### CODE REVIEW

**Comment by naoyam** [comment]
I'm not sure the change is safe. Added a failing test, `ValidateParallelize8`. May need to run multiple times, but I get:

```
C++ exception with description "aten_output_tensor.allclose( fusion_output_tensor.to(aten_output_tensor.dtype()), tolerance_values.second, tolerance_values.first) INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/test/test_gpu_validator.h":436, please report a bug to PyTorch.

Validation error in output 0 on line 15272 in file ../torch/csrc/jit/codegen/cuda/test/test_gpu.cpp.
  Detected abs error of: 3.57284
    absolute tolerance was set to 1.51992e-06
    and relative tolerance set to 2.23704e-06
```

**Comment by csarofeen** [comment]
So we need to find something that passes on 7 and asserts on 8? We can come back to this, it shouldn't be urgent.

**Comment by csarofeen** [comment]
@naoyam we might want to revisit the tests here quickly with the updated parallel validation. Otherwise just close this PR.

**Comment by naoyam** [comment]
The `ValidateParallelize7` test looks incorrect to me and is flagged as invalid by the new validator. 
```
Inputs:
  T0_g[ iS19{( ceilDiv(7, 3) )}, iS20{3} ], float
  T1_g[ iS12{( ceilDiv(( 6 * 7 ), 3) )}, iS13{3} ], float
Outputs:
  T4_g[ iblockIdx.x9{( ceilDiv(( 6 * 7 ), 3) )}, ithreadIdx.x10{3} ], float

%kernel_math {
T2_l[ iblockIdx.x17{( ceilDiv(7, 3) )}, iS18{3} ]
   = T0_g[ iS19{( ceilDiv(7, 3) )}, iS20{3} ]
   + double(1);
T3_l[ iblockIdx.x15{( ceilDiv(( 1 * 7 ), 3) )}, iS16{3} ]
   = broadcast( T2_l[ iblockIdx.x17{( ceilDiv(7, 3) )}, iS18{3} ] )
T4_g[ iblockIdx.x9{( ceilDiv(( 6 * 7 ), 3) )}, ithreadIdx.x10{3} ]
   = T3_l[ iblockIdx.x15{( ceilDiv(( 1 * 7 ), 3) )}, iS16{3} ]
   + T1_g[ iS12{( ceilDiv(( 6 * 7 ), 3) )}, iS13{3} ];
}
```

`BIDx` is used inconsistently between `tv2` and `tv4`. For the former, `BIDx` is bound to `7//3`, so only 3 blocks are used. For `tv4`, `BIDx` is used for `6 * 7 // 3`, so 14 blocks is used, which means we would need a communication from the first 3 blocks to the 14 blocks, thus requiring `tv2` (or `tv3`) to be placed in global memory. 

The `ValidateParallelize8` test seems fine now. Don't exactly remember why it had numerical errors before, but I suppose it was due to lack of syncthreads, which is now inserted properly.

I think we can close PR now.

**Pull request closed without merging**
