### PR TITLE
merge IterDomain

### PR DESCRIPTION
**Pull request by jjsjann123**
Does it make sense for us to propagate expanded_extent on merging broadcast domains?

### CODE REVIEW

**Review by csarofeen — APPROVED** [review]
Makes sense to me. CC @naoyam so he can confirm at some point.

**Comment by naoyam** [comment]
I think this makes sense. @jjsjann123 Can you please add a test case?

**Comment by jjsjann123** [comment]
> I think this makes sense. @jjsjann123 Can you please add a test case?

Thx. Will do.

I was thinking about adding a test that could show some breakage/bug and verify the fix before merging this. Will ping you once I got that in place.

**Comment by csarofeen** [comment]
Working on a PR to address this. Closing this one for now.

**Pull request closed without merging**
