### PR TITLE
fixing _batch_norm_impl_index(_backward) in shape expression

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #{issue number}

todo: ADD TEST CASE!

### CODE REVIEW

**Comment by jjsjann123** [comment]
Fixes this use case:

```
import torch
from torch.nn import Module
import torch.nn.functional as F

torch._C._jit_set_nvfuser_enabled(True)
torch._C._jit_set_texpr_fuser_enabled(False)
torch._C._jit_set_profiling_executor(True)
torch._C._jit_set_profiling_mode(True)
torch._C._jit_override_can_fuse_on_cpu(False)
torch._C._jit_override_can_fuse_on_gpu(False)
torch._C._jit_set_bailout_depth(20)

# [256, 512, 28, 28]
class Fusion(Module):
    def __init__(self):
        super(Fusion, self).__init__()
        self.bn = torch.nn.BatchNorm2d(512)

    def forward(self, inputs, resids):
        out1 = self.bn(inputs)
        #print(out1.shape, out1.stride(0), out1.stride(1), out1.stride(2), out1.stride(3))
        out2 = out1 + resids
        out3 = torch.relu(out2)
        return out3

if __name__ == "__main__" :
    inputs = torch.randn(256, 512, 28, 28, requires_grad=True, device="cuda", dtype=torch.float16).to(memory_format=torch.channels_last)
    resids = torch.randn(256, 512, 28, 28, requires_grad=True, device="cuda", dtype=torch.float16).to(memory_format=torch.channels_last)

    model = Fusion()
    model.to(memory_format=torch.channels_last)
    model.cuda()
    model.half()

    jit_model = torch.jit.script(model)
    #jit_model = model #torch.jit.script(model)

    out = None
    for idx in range(5) :
        #if idx == 3 :
        #    print(jit_model.graph_for(inputs, resids))
        out = jit_model.forward(inputs, resids)
```

**Comment by jjsjann123** [comment]
Tests passing, ready to be reviewed.

**Comment by jjsjann123** [comment]
Tests are passing. good for review now!

**Review by kevinstephano — APPROVED** [review]
LGTM

**Pull request merged**
