### PR TITLE
Bookend non compute

### LINKED ISSUE #2090: bookend `view` should be stripped from fusion
### 🚀 The feature, motivation and pitch

Currently the handling of view in scheduler is sub-optimal.

For views inside the fusion group that connects fusion, it makes sense, since this usually gives us a bigger graph and could be beneficial to fusion.
However, for `view` ops that surrounds a fusion, there's really no good reason to fuse those. Since `view` op is only a meta operation, leaving it outside of fusion could give us better codegen perf for now.

A few concrete issues that was raised by @kevinstephano:

1. Here’s another example of a fusion we just might not want to send to nvFuser as this is a transpose after Matmul2 and before the Output Linear of Multihead attention that is resulting in 2 kernels.  The 2 kernels take ~50 us whereas the single Transpose kernel in eager ~40us.

```
def nvfuser_fusion_id7(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1], contiguous=[True, True, True], dtype=DataType.Float)
    T1 = fd.ops.view(T0, original_shape=[768, 128, 64], new_shape=[64, 12, 128, 64])
    T2 = fd.permute(T1)
    T3 = fd.ops.set(T2)
    T4 = fd.ops.view(T3, original_shape=[64, 128, 12, 64], new_shape=[64, 128, 768])
    T5 = fd.ops.view(T4, original_shape=[64, 128, 768], new_shape=[8192, 768])
    fd.add_output(T5)

Arguments for fusion8:
Inputs:
tensor dtype: float sizes: (768, 128, 64, ) stride: (8192, 64, 1, ) pointer: 0x7f53a6000000
Outputs:
Launch Parameters: BlockDim.x = 128, BlockDim.y = -1, BlockDim.z = -1, GridDim.x = -1, GridDim.y = -1, GridDim.z = -1, Smem Size = 0
```

2. In the Feed-Forward Block, Gelu is getting decomposed and re-fused.  It is also sucking in the bookend views.  The result is a kernel that is running at 0.62x of the Eager Mode Gelu Kernel.  191 us vs 118 us.

```
def nvfuser_fusion_id10(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguous=[True, True], dtype=DataType.Float)
    T1 = fd.ops.view(T0, original_shape=[8192, 3072], new_shape=[64, 128, 3072])
    S2 = fd.define_constant(0.500000)
    T3 = fd.ops.mul(T1, S2)
    S4 = fd.define_constant(0.707107)
    T5 = fd.ops.mul(T1, S4)
    T6 = fd.ops.erf(T5)
    S7 = fd.define_constant(1.00000)
    T8 = fd.ops.add(T6, S7)
    T9 = fd.ops.mul(T3, T8)
    T10 = fd.ops.view(T9, original_shape=[64, 128, 3072], new_shape=[8192, 3072])
    fd.add_output(T1)
    fd.add_output(T10)

Arguments for fusion12:
Inputs:
tensor dtype: float sizes: (8192, 3072, ) stride: (3072, 1, ) pointer: 0x7f5148800000
Outputs:
Launch Parameters: BlockDim.x = 128, BlockDim.y = -1, BlockDim.z = -1, GridDim.x = -1, GridDim.y = -1, GridDim.z = -1, Smem Size = 0
```

Current plan is to add a quick pass that strips view-like op on the boundary of fusion. We'll see how that would impact the perf.

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #2090 

1. Adding bookend non_compute_node optimization.
    Added python test verifying that boundary non_compute meta ops are stripped from fusion.
2. Refactored getitem special handling in fusion.
    Put back the old getitem special handling, we are at least not failing the existing tests;
    getitem being explicitly supported by support op query, so it shouldn't be blocking fusion across getitem nodes.

### CODE REVIEW

**Comment by IvanYashchuk** [comment]
What happens with `broadcast_in_dim` in the beginning? I think it's also removed from the fusion, do we want it?

**Comment by jjsjann123** [comment]
> What happens with `broadcast_in_dim` in the beginning? I think it's also removed from the fusion, do we want it?

I think we'd want to keep `broadcast_in_dim`, but I also think they don't matter much!? unless it's cpu bounded and the meta operations are adding more overhead. Same thing applies to `broadcast_in_dim` on outputs where we have expanded outputs.
I didn't realize that `broadcast_in_dim` is also a non_compute_op. We can manually remove a few ops that we want to keep in the fusion.

I'll push a patch for this.

**Comment by kevinstephano** [comment]
Just as a funny note, if you peel off the `broadcast_in_dims`, you will expose a bookend view that would also be beneficial to remove. 

```
def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)     
    T1 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
    T2 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguous=[True, True], dtype=DataType.Half)                                                                                                                                                     
    T3 = fd.ops.broadcast_in_dim(T0, output_shape=[1, 1024, 768], broadcast_dims=[2])
    T4 = fd.ops.broadcast_in_dim(T1, output_shape=[1, 1024, 768], broadcast_dims=[2])
    T5 = fd.ops.view(T2, original_shape=[1024, 768], new_shape=[1, 1024, 768])
........
    fd.add_output(T5)
```

**Comment by jjsjann123** [comment]
sorry that's a separate bug in the code. I was removing all cascading bookend ops (or at least was intended to).

I think it also make sense for us to uniformly kick out all bookending non_compute_ops , including broadcast. As this would hide our problem with scheduling at this moment :slightly_smiling_face:

**Comment by jjsjann123** [comment]
> Just as a funny note, if you peel off the `broadcast_in_dims`, you will expose a bookend view that would also be beneficial to remove.
> 
> ```
> def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
>     T0 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)     
>     T1 = fd.define_tensor(symbolic_sizes=[-1], contiguous=[True], dtype=DataType.Float)
>     T2 = fd.define_tensor(symbolic_sizes=[-1, -1], contiguous=[True, True], dtype=DataType.Half)                                                                                                                                                     
>     T3 = fd.ops.broadcast_in_dim(T0, output_shape=[1, 1024, 768], broadcast_dims=[2])
>     T4 = fd.ops.broadcast_in_dim(T1, output_shape=[1, 1024, 768], broadcast_dims=[2])
>     T5 = fd.ops.view(T2, original_shape=[1024, 768], new_shape=[1, 1024, 768])
> ........
>     fd.add_output(T5)
> ```

in my local patched branch, all broadcast & views are being removed. You can also see this in the test here: https://github.com/csarofeen/pytorch/pull/2099/files#diff-f460358f17a4208ead1564040472d67b0325d6fb616c6c5326773304046f249cR187-R188

Also want to point out that `T5 = view(T2)` IS a bookend view to begin with. It didn't get removed for a bug. I'll push the patch soon~ish

**Pull request merged**
