### PR TITLE
Fix compilation error of `view_as_scalar`

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Fix a small bug while I was trying some random stuff.

Before this PR, the newly added test `FusionVectorComponentReduce_CUDA` create the following code that does not compile:
```CUDA
__global__ void kernel1(Tensor<std::complex<float>, 1> T0, Tensor<float, 1> T3) {
  NVFUSER_DEFINE_MAGIC_ZERO
  #pragma unroll 1
  for(nvfuser_index_t i7 = 0; i7 < T0.size[0]; ++i7) {
    Array<float, 2, 1> T1[1];
    T1[0] = 0;  // error: can not assign 0 to Array<float, 2, 1> type 
    T1[0]
       = erase_type(T0[(i7 * T0.stride[0])]);
    T3[i7] = 0.00000000000000000e+00;
    #pragma unroll
    for(nvfuser_index_t i8 = 0; i8 < 2; ++i8) {
      float T2[1];
      T2[0] = T1[0][i8];
      T3[i7]
        = T3[i7]
        + T2[0];
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
}

```

after this PR, the compilation error is fixed:
```CUDA
__global__ void kernel1(Tensor<std::complex<float>, 1> T0, Tensor<float, 1> T3) {
  NVFUSER_DEFINE_MAGIC_ZERO
  #pragma unroll 1
  for(nvfuser_index_t i7 = 0; i7 < T0.size[0]; ++i7) {
    Array<float, 2, 1> T1[1];
    T1[0] = {};  // Works fine
    T1[0]
       = erase_type(T0[(i7 * T0.stride[0])]);
    T3[i7] = 0.00000000000000000e+00;
    #pragma unroll
    for(nvfuser_index_t i8 = 0; i8 < 2; ++i8) {
      float T2[1];
      T2[0] = T1[0][i8];
      T3[i7]
        = T3[i7]
        + T2[0];
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
}

```

### CODE REVIEW

**Comment by naoyam** [comment]
How is it initialized? This is a question on the C++ spec, but does each value of `T[1][0]` and `T[1][1]` get initialized to some default value?

```
 T1[0] = {};  // Works fine
```

We could also do `T[0].set(0)`

**Comment by zasdfgbnm** [comment]
Searched online, and according to https://stackoverflow.com/a/7760368, seems that they are zero initialized. But for this case, do we care how it is initialized? It is replaced with something else immediately after the initialization.

**Comment by naoyam** [comment]
As long as it is indeed initialized, I don't think any value should be fine.

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
