### PR TITLE
Sort refactor, again.

### PR DESCRIPTION
**Pull request by csarofeen**

### CODE REVIEW

**Comment by naoyam** [comment]
Is this PR supposed to change `PersistentBufferResolution`? It seems the change overlaps with #1237.

**Comment by csarofeen** [comment]
For some reason this PR has all the changes in https://github.com/csarofeen/pytorch/pull/1240 which is what I'm trying to merge it into. No idea why.

**Comment by csarofeen** [comment]
Re-grabbed the branch and pushed it, should be good now.

**Review by naoyam — APPROVED** [review]
LGTM

**Pull request merged**
